### ISSUE TITLE
DefaultStyle.Font dont work.

### ISSUE THREAD

**Issue by t-tsuzuki-skgrp** [ClosedXML/ClosedXML#1006]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**
0.93.0, 0.93.1

**What is the current behavior?**
I can't change Font Style using  `XLWorkbook.DefaultStyle.Font.Font[Name|Size]`.
But I can change using `book.Style.Font.Font[Name|Size]`. ("book" is instanced XLWorkbook object)
below Version 0.92.1, both works.
 
**What is the expected behavior or new feature?**
Both property works.

**Did this work in previous versions of our tool?  Which versions?**
v0.92.1

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook.DefaultStyle.Font.FontName = "Century";
            XLWorkbook.DefaultStyle.Font.FontSize = 18;

            using(XLWorkbook targetBook = new XLWorkbook(XLEventTracking.Disabled))
            {
                IXLWorksheet targetSheet = targetBook.AddWorksheet("test");
                targetSheet.Cell(1, 1).Value = "Font Test";

                targetBook.SaveAs(@"C:\Users\xxxxx\Desktop\test_DefaultStyle.xlsx");
            }
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by Pankraty** [comment]
It's not a bug. The static property `DefaultStyle` refers to the style applied to entities by default. Say, when no particular font name or color specified for the cell it will be 'Calibry, 11pt'. Changing the global static style thus does not make any sense because it wouldn't affect how the Excel or LibreOffice treat the defaults. Moreover, if you'd change the global default to `Century, 18pt` all cells having such style would be saved with no font information (it is equal to the defaults, after all) but after you open that file in Excel there would be Calibri, 11pt again.

On the other hand, the instance property `IXLWorkbook.Style` is still available and editable. It determines what styles newly created worksheets will have.

**Comment by t-tsuzuki-skgrp** [comment]
I understand. Thank you.
Sorry about late reply.
