### ISSUE TITLE
Loading file with many merged cells got slower in version 0.94.0

### ISSUE THREAD

**Issue by riskcon** [ClosedXML/ClosedXML#1220]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

The issue started in Version 0.94.0 and is still present in 0.95.0-beta1.

**What is the current behavior?**

Loading a simple Excel file with many merged cells got 3-4 times slower in a test application. In a production application this difference was even more severe (2 seconds versus 20-30 seconds).

The output of a test application running two Excel files through the 0.93.1 and a newer version:

```
Using ClosedXML 0.93.1.0
Loaded 'NoMergedCells.xlsx' in 0,2579938s
Loaded 'MergedCells.xlsx' in 0,0192486s

Using ClosedXML 0.95.0.0
Loaded 'NoMergedCells.xlsx' in 0,2669296s
Loaded 'MergedCells.xlsx' in 0,0704385s
```

**What is the expected behavior or new feature?**

The DLL got so slow that we reverted back to 0.93.1 for our use case, because we have a lot of merged cells in the source files. A new version should not be much slower for no reason.

**Did this work in previous versions of our tool?  Which versions?**

Yes, in 0.93.1

## Reproducibility
I included two Excel files and a simple solution (VS2017) with a console application which spawns two different test runs, one with an old and one with a new version of ClosedXML.

**Code to reproduce problem:**

[ClosedXMLPerfTest.zip](https://github.com/ClosedXML/ClosedXML/files/3228266/ClosedXMLPerfTest.zip)

This is my first bug report, I hope the information is sufficient. I will watch the topic in case you need more information or can come up with a solution.

Best Regards, Robert

**Comment by Pankraty** [comment]
Can you please check this with the latest `develop`? There was a PR #1183 that addresses the performance of multiple merges and was merged when beta-1 had already been released.

Regardless, I think workbook loading can be improved by skipping all the validations performed during the merge. If I am not mistaken, while loading a workbook we call the same method `Merge()` which is called during the ordinary merging. And it looks for existing merged ranges in order to "unmerge" them, replaces the styles of cells to be merged, clears their contents and so on. If we omit this the loading should go faster. 

@riskcon would you like to submit a pull request for this? ;)

**Comment by Pankraty** [comment]
Turned out, we already skip checking the intersections during the loading, but we also had to skip cell styling. It helped, but I need examples showing the degradation from 2 seconds to 20-30 so I could investigate further.

**Comment by riskcon** [comment]
@Pankraty Thank you for the very fast reply! The import from an Excel-file got so slow with the newer version of ClosedXML that we thought it was broken/hanging alltogether at first. I will test it with the latest develop as soon as I have the time.
