### ISSUE TITLE
Still ridiculous memory usage on saving large Excel files

### ISSUE THREAD

**Issue by jholovacs** [ClosedXML/ClosedXML#1241]
ref #86 where 0.93 was supposed to fix this, I am trying to build a workbook with several 1M-row sheets.  Total roughly 16M rows altogether.  On saving, I run out of memory after it exhausting 128GB of RAM.  Using 0.94 because there were breaking changes made after this.  I could understand a few gigs, but...

**Comment by igitur** [comment]
I suggest you look to use another library for that amount of data: EPPlus or working with the file directly using OpenXML.

**Comment by jholovacs** [comment]
Sigh, I have a mountain of old code using this library.  While there is a large amount of data, it seems like the memory utilization is seriously broken.  Do you know where the issue lies?  I might take a stab at it myself.

**Comment by igitur** [comment]
Possible improvements can be made by deduplicating formulas and using a formula repository (see #1201 ). Possibly a string pool could also reduce memory usage. But this will have to be done without affecting performance. Maybe @pankraty has some other ideas?

**Comment by Pankraty** [comment]
Come on, #86 was about out of memory on 50K rows and now it fails on "just" 16M rows. We are progressing but not _that_ fast. 
Be realistic, ClosedXML was not designed to operate with such amounts of data as it processes everything in memory. In order to create such large files some kind of stream API is needed.

**Comment by jholovacs** [comment]
@Pankraty that doesn't make sense to me; it really shouldn't be a "spectrum" issue, where there is a continuum of small incremental changes that are being made to more efficiently use memory.  This looks like a case where there is an obviously poorly scaling mechanism _in one spot_ that is doing something poorly with large datasets, like an O(n<sup>2</sup>) complexity issue.  The data in the file consisted of about 3GB of information, but memory utilization is like 50 times that size when saving?  This isn't a matter of "improving", there is an obviously poorly performing mechanism in the code that is causing this issue.

**Comment by igitur** [comment]
Us mortals are looking forward to your pull request that fixes this obvious error on our side.

**Comment by jholovacs** [comment]
You know what? Never mind.  If you want to be sarcastic and hostile, there's no point in helping out.  I don't like working with children.

**Comment by igitur** [comment]
Ok, maybe that came across a bit harsh. It was very much tongue-in-cheek. 

But look at it from our side. We're at issue 1241 already, with people coming here, demanding features, better performance and lower consumption. Most of these people use ClosedXML in their day-job, yet expect us to provide some kind of headless version of Excel with the same performance and we're expected to do this in our sparetime, for free.

That's not how open-source works. If you want something that the library doesn't provide, download the code and fix it. It would be ideal if you could then contribute those code changes back to the project so that others may benefit from it too. But you don't have to. The code is on here for free and you can do with it want you want, as long as you subscribe to the conditions of the MIT license. 

When people log issues, I'll try to fix them, only because it's interesting to me and might benefit me in my own use of ClosedXML in the future. But when people come with comments like "why is this issue closed?" and start throwing big-O notation without even having downloaded the code, I can't take them very seriously. Long story short... if you want street cred around here, submit a PR. That's how I began to trust @pankraty.

**Comment by parautenbach** [comment]
@jholovacs I've found that Excel for any application will get slow with several millions of records. Perhaps consider switching to an Access DB, which will perhaps be easiest for now, but I think you should invest in a proper DB for that level of processing. I doubt that limits you're running into are due to the use of this library. In the long run, your solution won't scale, even if the library gets optimised somewhat. Also, keep in mind that people (not me) are investing their own time to provide the community with something useful – for free.

**Comment by jholovacs** [comment]
TBH street cred and trust are not considerations of mine, I just want to
get it working for my admittedly extreme edge case.  This was the reason I
asked if there was a section of code that was suspected of being the memory
hog, because it was my intention to clone the repo and look into improving
it in terms of memory utilization.  There does seem to be a big-O
complexity problem here, as I note it seems to take geometrically more
resources as rowcount increases linearly, and I do have some skill and
experience with these sorts of things.  I don't think I deserve to be
mocked for that.

I'm very aware this is not a good use of Excel... like I said, I have a
mountain of old code where scaling was never a serious consideration.  My
options in the short term are, "somehow make this work with the current
library" or "tell our customers they can't get ridiculous Excel-based
reports"... I think most people can imagine what the bosses want to happen.

I'm okay with this being slow... I don't think that anyone asking for this
is really expecting performance out of an insane abuse of Excel.  I just
need to be able to (eventually) make the document, and right now it seems
impossible even when we throw a huge machine with 128GB of RAM at it.  I
did want to see what I could do to handle large datasets, but it seems the
developers on the project would prefer something else.
