### ISSUE TITLE
Unable to get the border color correctly

### ISSUE THREAD

**Issue by chiikin** [ClosedXML/ClosedXML#1320]
Although I can get the cell's border style, I can't get the correct color of the cell's border。
my code:
Fragment 1：
```csharp
if (border.TopBorder != XLBorderStyleValues.None)
{
borderStyles.Add(new KeyValuePair<string, string>("border-top", GetBorderStyle(border.TopBorder, border.TopBorderColor, theme)));
}
```
GetBorderStyle：
```csharp
private string GetBorderStyle(XLBorderStyleValues sytle, XLColor xlColor, IXLTheme theme)
        {
            string rgbColor = GetHtmlRgbString(xlColor, theme);
            string lineStyle;
            switch (sytle)
            {
                case XLBorderStyleValues.Medium:
                    lineStyle = " 2px solid";
                    break;
                case XLBorderStyleValues.Thick:
                    lineStyle = " 3px solid";
                    break;
                case XLBorderStyleValues.Thin:
                default:
                    lineStyle = " 1px solid";
                    break;
            }
            return lineStyle == null ? null : (rgbColor + lineStyle);
        }
```

GetHtmlRgbString:
```csharp
private string GetHtmlRgbString(XLColor xlColor, IXLTheme theme)
        {
            switch (xlColor.ColorType)
            {
                case XLColorType.Color:
                    return GetHtmlRgbString(xlColor.Color);
                    break;
                case XLColorType.Theme:
                    //return 
                    var xlThemeColor = theme.ResolveThemeColor(xlColor.ThemeColor);
                    return GetHtmlRgbString(xlThemeColor.Color, xlColor.ThemeTint);
                case XLColorType.Indexed:
                    var color=XLColor.IndexedColors[xlColor.Indexed];
                    if (xlColor.Indexed < 64)
                        return GetHtmlRgbString(XLColor.FromIndex(xlColor.Indexed).Color);
                    else if (xlColor.Indexed == 64)
                        return GetHtmlRgbString(XLColor.Black.Color);
                    else
                        return GetHtmlRgbString(xlColor.Color);
                    break;
                default:
                    return "";
            }
        }
```
in GetHtmlRgbString method,I got the black color(#FF000000) of type xlcolortype.color from xlcolor.color, but the cell color should be "#FF3196FA" of type xlcolortype.color

**Comment by Pankraty** [comment]
Please use the issue template:

## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

Complete this.

**What is the expected behavior or new feature?**

Complete this.

**Did this work in previous versions of our tool?  Which versions?**

Yes/No/v0.XX

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    // Code standards:
    // - Fully runnable. I should be able to copy and paste this code into a 
    //   console application and run it without having to edit it much.
    // - Declare all your variables (this follows from the previous point)
    // - The code should be a minimal code sample to illustrate issue. The code 
    //   samples on the wiki are good examples of the terseness that I want. Don't
    //   post your full application.
}
```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)
