### ISSUE TITLE
Xlsx saved via MemoryStream gives 'We found a problem with some content'.., while same saved to disk works

### ISSUE THREAD

**Issue by amv-** [ClosedXML/ClosedXML#1340]
- [x] Bug
- [ ] Feature

Not sure it's a bug.

Version 0.93.1

Using ClosedXml to generate the excel from a datatable, I used the standard code where I save it to a MemoryStream and then push it into an http response. That works fine but when trying to open I get the error message 'We found a problem with some content.. '

Then I tried to save the file directly to disk and surprisingly enough, opening the file works just fine.

I compared the two generated files and they seem to have identical content files after renaming the files as zip (except for a minor timestamp in a .psmdcp file under /package/services/metadata/core-properties.)
Another difference is that the one saved with MemoryStream is almost double in size.

I attach the sample files here:
test1.xlsx - saved directly as file on disk, works fine
test2.xlsx - saved via MemoryStream, not working

[test1.xlsx](https://github.com/ClosedXML/ClosedXML/files/4104419/test1.xlsx)
[test2.xlsx](https://github.com/ClosedXML/ClosedXML/files/4104420/test2.xlsx)

Hoping someone has a clue as to why is this happening.

**Comment by igitur** [comment]
You completely deleted the issue template and left out lots of important information.

**Comment by nhaberl** [comment]
still happens when using InsertTable(IEnumerable)

**Comment by jahav** [comment]
@nhaberl  I am not sure if your problem is different than the one @amv-  reported, but the original problam was an error in the API or sometwhere. 
test1.xlsx is 8582 bytes long 
test2.xlsx is 14573 bytes long
test2.xls zip file has extra HTML page appended to the ZIP stream with title "Cannot redirect after HTTP headers have been sent."
![image](https://user-images.githubusercontent.com/7634052/191487062-1790a4c0-913b-4648-9e9c-42416e8928a1.png)

I guess the controller tried to do something, failed and appended an error page to the zip stream. Error is not caused by ClosedXML.

**Comment by cemerson** [comment]
Did you ever find the solution to this? I have the exact same issue:
* Saving to `workbook.SaveAs("C:\Temp\MyFile.xlsx")` --> works great
* Saving to `byte[] via workbook.SaveAs(ms) // then sending as Response.BinaryWrite(bytes)` --> results in corrupt Excel file

**Comment by amohar** [comment]
For me, it was a stupid mistake. I was rewinding the stream to 0, which is of course ok, but I was opening-or-creating the file to write to, which meant the file wasn't truncated if it existed. This further meant that if the file was larger than the data in mem stream, it would tail the closed XML document and was considered a problem. Make sure you always rewind the stream and always recreate the file.
