### ISSUE TITLE
Calculation engine context

### ISSUE THREAD

**Issue by igitur** [ClosedXML/ClosedXML#1415]
Another thing to consider for 0.96.

Currently, functions like `=ROW()` cannot evaluate, because the formula implementation has no idea of the call cell's address. I propose adding a parameter `CalculationEngineContext context` to the formula's delegate definition.

This object can contain all the properties we need for implementing more formulas and can be extended later. 

Things I can think of to include right now:
- The original cell's address
- The current cell's address (see below)
- An instance to `XLCalcEngine` or `CalcEngine`
- The `CultureInfo` needed for evaluation

Regarding the cells, imagine in `A1` you have `=B1`, and in `B1` you have `=LEN(C1)`. Then you call `Console.WriteLine(ws.Cell(A1).Value)`. `A1` would be the original cell's address and as you evaluate through the formula tree, `B1` and `C` would be the "current" cell's address. We can decide on better names later.

I tried to do a quick proof of concept, but there are some challenges. Obviously the static method `XLWorkbook.Evaluate("=ROW()")` will never work.

But we also need to decide whether this context variable is generated and stored in the `Expression` subclasses or passed through as a parameter in `ws.Evaluate()`.

Original issue: #187.

**Comment by Pankraty** [comment]
My 2 cents.

If we stick to a single-thread approach we can also specify context-specific properties in `XLCalcEngine` instance. I am not fond of this idea, but it can reduce the number of allocations (we won't create a new instance of a context for every cell we evaluate).

Alternatively, we can make `XLCalcEngine` stateless, and provide all the necessary data via context. With this, we'll be able to support a parallelizm in formula evaluation sometime in the future.

A side note. To support contextual computations we also have to replace direct access to `XLCell.Value`. Instead, we need something like this (_very schematically_):

```
XLCell 
{
  public object Value => GetValue(context: null);

  internal object GetValue(XLCalcContext context)
  {
     // get value or compute formula
  }
}

XLCalcEngine
{
  object Evaluate()
  {
    // instead of cell.Value use cell.GetValue(currentContext);
  }
}
```

**Comment by jahav** [comment]
CalcContex will be added in the #1812. It has properties from the proposal (original cell's address, CalcEngine and CultureInfo). 
Current cell hasn't been included, because the plan (in the future, not the #1812 ) is to have multiple workers work in parallel and they can't share a context.

AST nodes are supposed to be completely stateless and keep all variable data for a single cell/array calculation in the CalcContext. 

I hope to share formula/abstract syntax tree across multiple cells to decrease memory pressure (e.g. if we have a column full of copied formulas (e.g. `LEN(A1)` in `B1`, `LEN(A2)` in `B2` and so on), they could share same AST if AST used RC style reference (e.g. in `LEN(R[0]C[-1])` for B1 and `LEN(R[0]C[-1])` B2).
