### ISSUE TITLE
Using ClosedXML from nested class library requires OpenXml 2.7.2.0 (and not newer)

### ISSUE THREAD

**Issue by sborkman** [ClosedXML/ClosedXML#1433]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

If you are logging a possible bug or feature request, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

Yes, I downloaded the source for the develop branch, compiled the ClosedXML DLL, and referenced it from my project and the problem still occurred.

**Version of ClosedXML**

I'm using 0.95.2 via Nuget.

**What is the current behavior?**

I have a WPF project the references a class library that references a class library that uses ClosedXML. When the nested class library attempts to load the ClosedXML assemblies, I get this error:

![Exception](https://user-images.githubusercontent.com/11967547/82085998-d7b16780-96bb-11ea-9680-12a36c08fad8.png)

System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.10.1.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The system cannot find the file specified.
  Source=AnotherClassLibrary
  StackTrace:
   at AnotherClassLibrary.Class1.go() in C:\Users\myuserid\Source\Repos\ExploreBug\AnotherClassLibrary\Class1.cs:line 17
   at SomeClassLibrary.Class1.go() in C:\Users\myuserid\Source\Repos\ExploreBug\SomeClassLibrary\Class1.cs:line 13
   at ExploreBug.MainWindow.Button_Click(Object sender, RoutedEventArgs e) in C:\Users\myuserid\Source\Repos\ExploreBug\ExploreBug\MainWindow.xaml.cs:line 30
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at ExploreBug.App.Main()

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'DocumentFormat.OpenXml, Version=2.7.2.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17' or one of its dependencies. The system cannot find the file specified.

The same problem may have been reported here:
[CLosedXml 0.92 won't load OpenXml 2.7.2  #1043](https://github.com/ClosedXML/ClosedXML/issues/1043)

**What is the expected behavior or new feature?**

Don't crash when the ClosedXML and OpenXml assemblies load.

**Did this work in previous versions of our tool?  Which versions?**

This problem was introduced in version  0.88.0.
There is no error when using version 0.87.1.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

The problem happens when a WPF app (ExplorerBug) references a class library (SomeClassLibrary), which references a class library (AnotherClassLibrary), and AnotherClassLibrary attempts to use ClosedXML. When the ClosedXML assemblies load, I get an error saying the OpenXml v2.10.1.0 assembly failed to load because OpenXml 2.7.2.0 can't be found. What!?

A work-around is to add a reference to ClosedXML for either ExplorerBug or SomeClassLibrary. Very strange.

**Code to reproduce problem:**

[Reproduce the Problem.zip](https://github.com/ClosedXML/ClosedXML/files/4636664/Reproduce.the.Problem.zip)

```c#
namespace ExploreBug
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            SomeClassLibrary.Class1.go();
        }
    }
}

namespace SomeClassLibrary
{
    public class Class1
    {
        public static void go()
        {
            AnotherClassLibrary.Class1.go();
        }
    }
}

namespace AnotherClassLibrary
{
    public class Class1
    {

        public static void go()
        {
            XLWorkbook workbook = new XLWorkbook();
        }

    }
}

```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by sborkman** [comment]
I will also add that enabling auto-generate binding redirects on ExploreBug is not enough.
To fix this problem, auto-generate binding redirects must be enabled on SomeClassLibrary.
Enabling it on AnotherClassLibrary is insufficient to fix the problem.
Is this the expected behavior? I would expect the ClosedXML Nuget artifact would be compiled in such a way that it would work with newer versions of OpenXml without the need for additional binding redirects, but perhaps that's just how it works. Does anyone know?

**Comment by sborkman** [comment]
Interestingly, none of the work-arounds or fixes helped in my actual real-world project (where I first bumped into this issue). The work-around I'm using for my real-world project is to refer to (load) the ClosedXML assemblies in "SomeClassLibrary" before I use ClosedXML from "AnotherClassLibrary". Not particularly satisfying, but at least I'm not stuck anymore.

**Comment by igitur** [comment]
Hi. See https://stackoverflow.com/questions/43257670/dependent-dlls-of-a-nuget-package-not-copied-to-output-folder 

This is just a feature of the build system where it would not copy dependent assemblies if there is no _direct_ code using them. Did you ever check that your `ExploreBug`'s output folder contains `DocumentFormat.OpenXml.dll`? You would have noticed that it does not, hence the complaint that it can't find the file. 

A quick google search reveals the solution is either to explicitly reference a class from `DocumentFormat.OpenXml` or add a reference to its NuGet package in your `ExploreBug` project.

This is not a ClosedXML issue. I hope this settle this issue for once and for all.

**Comment by tonyzhangemtek** [comment]
Hi. I just wanted to check if the issue I'm running into is the same issue as this?

I'm using ClosedXML in a [class] called 'NavisworksClassLibraryPlayground' written for another program. The [class] is located in C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/NavisworksClassLibraryPlayground. ClosedXML.dll is also copied into the same folder when the project is built.

From below log we can see it doesn't know where to find ClosedXML.dll. Is this an expected behavior as mentioned above? 

		FusionLog	"=== Pre-bind state information ===
\r\nLOG: DisplayName = ClosedXML, Version=0.100.3.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b\n (Fully-specified)
\r\nLOG: Appbase = file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/
\r\nLOG: Initial PrivatePath = NULL
\r\nCalling assembly : NavisworksClassLibraryPlayground, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
\r\n===
\r\nLOG: This bind starts in default load context.
\r\nLOG: Using application configuration file: C:\\Program Files\\Autodesk\\Navisworks Simulate 2021\\Roamer.exe.Config
\r\nLOG: Using host configuration file: 
\r\nLOG: Using machine configuration file from C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\config\\machine.config.
\r\nLOG: Post-policy reference: ClosedXML, Version=0.100.3.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML/ClosedXML.DLL.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML.EXE.
\r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML/ClosedXML.EXE.
\r\n"	string

**Comment by tonyzhangemtek** [comment]
> Hi. I just wanted to check if the issue I'm running into is the same issue as this?
> 
> I'm using ClosedXML in a [class] called 'NavisworksClassLibraryPlayground' written for another program. The [class] is located in C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/NavisworksClassLibraryPlayground. ClosedXML.dll is also copied into the same folder when the project is built.
> 
> From below log we can see it doesn't know where to find ClosedXML.dll. Is this an expected behavior as mentioned above?
> 
> > FusionLog	"=== Pre-bind state information ===
> > \r\nLOG: DisplayName = ClosedXML, Version=0.100.3.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b\n (Fully-specified)
> > \r\nLOG: Appbase = file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/
> > \r\nLOG: Initial PrivatePath = NULL
> > \r\nCalling assembly : NavisworksClassLibraryPlayground, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
> > \r\n===
> > \r\nLOG: This bind starts in default load context.
> > \r\nLOG: Using application configuration file: C:\Program Files\Autodesk\Navisworks Simulate 2021\Roamer.exe.Config
> > \r\nLOG: Using host configuration file:
> > \r\nLOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
> > \r\nLOG: Post-policy reference: ClosedXML, Version=0.100.3.0, Culture=neutral, PublicKeyToken=fd1eb21b62ae805b
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML/ClosedXML.DLL.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/ClosedXML/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/Loaders/dbx/ClosedXML/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/internalplugins/ClosedXML/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/plugins/ClosedXML/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/dependencies/ClosedXML/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML.EXE.
> > \r\nLOG: Attempting download of new URL file:///C:/Program Files/Autodesk/Navisworks Simulate 2021/stubplugins/ClosedXML/ClosedXML.EXE.
> > \r\n"	string

OK I found a solution to this problem:
https://stackoverflow.com/questions/1373100/how-to-add-folder-to-assembly-search-path-at-runtime-in-net
