### ISSUE TITLE
Bad performance when working with styles (>200 000 cells)

### ISSUE THREAD

**Issue by timka3115** [ClosedXML/ClosedXML#1440]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [x] Feature

**Version of ClosedXML**

0.95.2

When I set different styles for 200 000 cells it takes too much time (~8 sec, Intel Core i7, Memory 16Gb).

**What is the expected behavior or new feature?**

Should works much faster, 2 sec for example will be good result.

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

Try to run code below

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;
using System;
using System.Linq;

namespace ClosedXmlPerformanceTest
{
    class Program
    {
        static string Chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        static Random random = new Random();

        static void Main(string[] args)
        {
            TestStyles();
        }

        static void TestStyles()
        {
            const int columnCount = 20;
            const int rowCount = 10000;

            var workbook = new XLWorkbook(XLEventTracking.Disabled);
            var worksheet = workbook.AddWorksheet();
            GenerateData(worksheet, rowCount, columnCount);

            var watch = System.Diagnostics.Stopwatch.StartNew();
            for (var column = 1; column <= columnCount; column++)
            {
                for (var row = 1; row <= rowCount; row++)
                {
                    var cell = worksheet.Cell(row, column);
                    
                    var styles = cell.Style;

                    var font = styles.Font;

                    font.Bold = true;
                    font.FontSize = 13;
                    font.FontColor = XLColor.Red;

                    var alignment = styles.Alignment;
                    alignment.Horizontal = XLAlignmentHorizontalValues.Center;
                    alignment.Vertical = XLAlignmentVerticalValues.Justify;

                    var border = styles.Border;
                    border.BottomBorder = XLBorderStyleValues.Medium;
                    border.LeftBorder = XLBorderStyleValues.Medium;
                }
            }
            watch.Stop();
            Console.WriteLine($"Setting styles elapsed {watch.ElapsedMilliseconds}ms.");
        }

        private static void GenerateData(IXLWorksheet worksheet, int rowCount, int columnCount)
        {
            for (var column = 1; column <= columnCount; column++)
            {
                for (var row = 1; row <= rowCount; row++)
                {
                    var cell = worksheet.Cell(row, column);
                    cell.SetValue(GetRandomTextValue(16));
                }
            }
        }

        private static string GetRandomTextValue(int maxLength)
        {
            return new string(Enumerable.Repeat(Chars, maxLength)
                .Select(s => s[random.Next(s.Length)])
                .ToArray());
        }
    }
}

```
- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

I investigated this problem and noticed that each style modification executes XLStyle.Modify() method and inside it _container.ModifyStyle(modification). As a solution I would like to suggest to add methods IXLStyle.BeginUpdate() and IXLStyle.EndUpdate() to run _container.ModifyStyle() only once at the end of styles modification.

**Comment by Pankraty** [comment]
That's an interesting proposal and I am sure it would have a good performance impact. Although it may complicate the code and raises open questions such as "what happens if `EndUpdate()` is never called"  and "will such unfinished operations not affect the memory consumption".

On the other hand, there is a way to achieve the same result more easily by publicly exposing the existing internal method `XLStyle.Modify()`. It requires making all `XL***Key` structs to be public as well, and the usage may be not so clear, but the effect is definitely positive: in your example (but with 60 columns instead of 20) the execution time changes from 11500 ms to 1950 ms.

See #1442

**Comment by timka3115** [comment]
Thanks for quick response and another good proposal for solving this issue! I am very appreciate your contribution

> See #1442

**Comment by vbjay** [comment]
Begin/end update is a standard operation throughout .net. See
*https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.beginupdate?view=netcore-3.1
<https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.beginupdate?view=netcore-3.1>*
 and
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.endupdate?view=netcore-3.1#System_Windows_Forms_ListView_EndUpdate
for an example. They even mention not calling endupdate the same number of
times as begjnupdate.  I don't like exposing internals like that.

**Comment by jahav** [comment]
I am not in favor of `BeginUpdate()` and `EndUpdate()`. It's used 15 times in BCL (per [NetFx referencesource](https://referencesource.microsoft.com/#q=BeginUpdate) and not even once in dotnet runtime repo on github. Discoveribility and semantic of API seems poor.

If there really is a need to set 200k cells, there are at least two options that are feasible. Either of them seem like something a developer can use and figure out. There are few others, like using row column/row styles.

### Use bulk options:
Instead of setting each cell, take a range and set styles on that

```csharp
var styles = worksheet.Range(1, 1, rowCount, columnCount).Style;
var font = styles.Font;

font.Bold = true;
font.FontSize = 13;
font.FontColor = XLColor.Red;
```
That takes about 1.3 second comapred to original 2.9 seconds.

### Copy style
Other option is to set a style to a cell and copy it to the range. This avoids a lot of unnecessary updates from previous version, because each call to ModifyStyle needs to update each cell repeatedly instead of doing it just once.

```csharp
var style = worksheet.Cell(1,1).Style;
var font = style.Font;
font.Bold = true;
// ... Rest
      
worksheet.Range(1, 1, rowCount, columnCount).Style = style;
```
This one takes 0.2 second vs 2.9 seconds in the original one.


Because of this, I am closing the issue.
