### ISSUE TITLE
Cannot obtain numeric value from custom formatted cell

### ISSUE THREAD

**Issue by timka3115** [ClosedXML/ClosedXML#1512]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.3

**What is the current behavior?**

If I place cell.RichText.ToString() between two statements cell.GetDouble() than test failed.  I use getters from public API but it seems to me XLCell.RichText.ToString() change internal state of cell's value.

**What is the expected behavior or new feature?**

Using XLCell.RichText.ToString() doesn't break XLCell.GetDouble() logic.

**Is this a regression from the previous version?**

yes

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
 static void Main(string[] args)
        {
            using (var workbook = new XLWorkbook(@"C:\number_format_test.xlsx"))
            {
                var worksheet = workbook.Worksheet(1);
                var cell = worksheet.Cell("A1");
                Assert.AreEqual(XLDataType.Number, cell.DataType);

                Assert.AreEqual(1000, cell.GetDouble());
                Assert.AreEqual("1,000.00 EUR", cell.RichText.ToString());  // actually cell.HasRichText = false but we ignore it
                Assert.AreEqual(1000, cell.GetDouble());
            }
        }
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[number_format_test.xlsx](https://github.com/ClosedXML/ClosedXML/files/5188173/number_format_test.xlsx)

**Comment by igitur** [comment]
Hi,

Yes, the current behaviour is that if you call `cell.RichText` the current contents of the cell is automatically converted to rich text and you can then apply your chosen style. The cell's number format is applied when converting to rich text. Only strings can be rich text. Numbers cannot.

During the last `cell.GetDouble()` ClosedXML attempts to parse the string value back to a double, but because of your unique number format with the `EUR` in it, it fails.

So this is all behaviour by design. There is, however, a PR to remove the automatic conversion to rich text and make it an explicit action. See #1396 .

My advice would be to avoid calling `cell.RichText` unless you really want to convert the contents to rich text. 

Thanks for the good code sample.

**Comment by timka3115** [comment]
Thank you for quick response. Indeed, sometimes behavior of API methods is confused.
