### ISSUE TITLE
Strong-name sign ClosedXML and deprecate ClosedXML.Signed package

### ISSUE THREAD

**Issue by augustoproiete** [ClosedXML/ClosedXML#1547]
**Do you want to request a *feature* or report a *bug*?**
- [x] Feature

**Did you test against the latest CI build?**
- [x] Yes

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.3

**What is the current behavior?**

At the moment there are two distinct nuget packages for ClosedXML:
- [ClosedXML](https://www.nuget.org/packages/ClosedXML/) (**not** signed with strong-name)
- [ClosedXML.Signed](https://www.nuget.org/packages/ClosedXML.Signed/) (**signed** with strong-name)

Given improvements in .NET Core (re: binding redirects) and recent updates to Microsoft's guidance on strong-naming, I'd suggest we strong-name the `ClosedXML` assembly, and retire the `ClosedXML.Signed` package.

Any objections before I put together a PR?

---

Related links: 

- [Strong Name Signing, dotnet/corefx](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)
- [Strong naming guidance, docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/strong-naming)
- [Build great libraries using .NET Standard](https://www.youtube.com/watch?v=hLFyycJVo0I&feature=youtu.be&t=1470)

**Comment by igitur** [comment]
Would that not break non-strong-named dependent assemblies?

**Comment by augustoproiete** [comment]
@igitur Assuming this change would be released with ClosedXML 0.96.0, then it would only break for users that:

a) An app targeting .NET Framework uses the new version 0.96.0
**and**
b) They do not use binding redirects

As of .NET Framework 4.5.1, projects in VS automatically generate binding redirects, thus for most people I'd expect it to Just Work™

![image](https://user-images.githubusercontent.com/177608/97186549-2fcaba80-1780-11eb-9a37-9d1cd6dffb5a.png)

**Comment by igitur** [comment]
@Pankraty Your thoughts on this?

**Comment by Pankraty** [comment]
I introduced a signed version of ClosedXML a few years ago when I was working on a project with 10+ years old history, 300+ projects in solution, and requirements to have all libraries signed. At that point, it was easier to release a signed version of ClosedXML than to convince all parties involved in that product development.

But since then they've discarded the requirement regarding signing the assemblies (and I've changed the project too) so the original reasons are not relevant anymore. The only use case which comes to my mind is the automatic performance test (#1225) that loads a signed version from nuget and builds non-signed one from source code and compares their performance. I did not finish that PR because these tests were too slow but I think BenchmarkDotNet became faster lately so maybe we have to give it another chance. In that case, removing the signed version will be undesirable.

**Comment by augustoproiete** [comment]
@Pankraty I'm not sure I completely follow the reason where removing the signed version will be undesirable, but in the spirit of moving things forward, I suggest we break this issue into three different ones that can be done (or not done) at different points in time:

#### 1-) Strong-name sign the main ClosedXML assembly moving forward, but keep ClosedXML.Signed
Signing the `ClosedXML` is the only thing that really matters at the end of the day. It gives library authors that want to sign their libraries to be able to take a dependency on `ClosedXML` instead of `ClosedXML.Signed`, as well as application developers to sign their apps without having to either take a dependency on `ClosedXML.Signed` or use `StrongNamer` (or a similar tool) to sign `ClosedXML` during build.

New versions of `ClosedXML.Signed` can continue to be published on nuget.org together with `ClosedXML` and both will be strong-name signed, with the same key. Identical assemblies.

#### 2-) Mark the ClosedXML.Signed nuget package as deprecated on nuget.org
This is not required, but a good thing to do once ClosedXML is signed. [Marking the `ClosedXML.Signed` package as deprecated on nuget.org](https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/) signal to developers they should move to `ClosedXML` when possible. Marking the package as deprecated on nuget.org doesn't break anything and people can continue to use if they wish... It's just for informational purposes.

#### 3-) Stop releasing new versions of ClosedXML.Signed (one day)
This is not required and can be done at a later time whenever it makes sense (perhaps after #1225 is merged).

The `ClosedXML.Signed` package can continue to exist forever if we want... Not a problem.

---

I'm happy to modify PR #1552 to bring back the `Closed.Signed` package, and only add the strong-name to `ClosedXML`, so that we'll end up with both packages signed `ClosedXML` and `ClosedXML.Signed`.

Let me know if you want to pursue this route.

**Comment by Pankraty** [comment]
@augustoproiete, sorry, I misinterpreted your original suggestion. I captured that you want to retire the signed version but totally missed you proposed to sign the primary version instead 🤦 

In fact, I don't have any strong arguments on either solution - whether to sign the assembly or not. We used to have quite a few issues reporting that some assemblies can't work together, and there have not been such reports awhile, and I don't know if it's because we stopped signing our assembly or because binding redirects started to work better. 

Nuget statistic says non-signed version is downloaded 100 times more often than a signed one (658,998 vs 6,651 for the last version) and this proves that the vast majority of the users is OK with not signing their assemblies. Do we want to potentially break their workflow? Besides, ClosedXML was not signed up till 2011th, then we stopped signing it in 2018th forcing part of our users to switch to ClosedXML.Signed, and now we are about to roll this back and force them to switch again... Does not look like a consistent policy, does it? 

The current state seems flexible enough - the users can choose either of two packages depending on their needs, and the only argument against I found so far is Microsoft's statement

> DO NOT publish strong-named and non-strong-named versions of your library. For example, Contoso.Api and Contoso.Api.StrongNamed.
> Publishing two packages forks your developer eco-system. Also, if an application ends up depending on both packages the developer can encounter type name conflicts. As far as .NET is concerned they are different types in different assemblies.

For me, this does not look convincing enough: we do not _fork our developer ecosystem_: we suffer from CI pipeline running twice as long but this is a small price. As for the application having references to both assemblies - from my past experience, I'd count this as a blessing - being able to upgrade the reference in _my_ part of the application not affecting the parts of the other teams :)

But again, these are not strong arguments, I can live without a strongly-named assembly too.

I'll reference #942 for history.

**Comment by augustoproiete** [comment]
@Pankraty No worries!

Indeed, binding redirects got a lot better since .NET 4.5 and the undesired side-effects of strong-naming assemblies are mostly gone in the .NET world, and completely gone for .NET Core/.NET 5 thus it can only get better with time.

Thus if you don't don't have a strong opinion on either side, I suggest we move forward with the plan above and sign ClosedXML only, keeping ClosedXML.Signed for a while to give people (including the core dev team) more time to move to the newest ClosedXML that will also be strong-name signed.

---

Re: _"we do not fork our developer ecosystem_" - We actually do. What they mean here is that other developers that want to extend ClosedXML and build other packages on top of it, now have to choose between ClosedXML and ClosedXML.Signed to take a dependency on: **That's the fork**.

As an example, let's look at popular packages (according to nuget.org) that extend ClosedXML today:
- [`DoddleReport.OpenXml`](https://www.nuget.org/packages/DoddleReport.OpenXml/), depends on `ClosedXML`
- [`DataBooster.DbWebApi.SqlServer`](https://www.nuget.org/packages/DataBooster.DbWebApi.SqlServer/), depends on `ClosedXML.Signed`

![image](https://user-images.githubusercontent.com/177608/100187700-0b691780-2ebf-11eb-9ed6-422936b87c14.png)

As you can imagine, an app that needs to use both packages in their application will most likely run into issues using these together. In the best case scenario, the app runs but they won't be able to share any ClosedXML instances between these libraries, because in the eyes of .NET Framework the assemblies are not the same, and thus the types are also not the same, despite having the same namespace & name. In the worst scenario the app won't even run and will thrown a `TypeInitializationException`.

---

Another reason for signing the main assembly is the classic scenario that affects anyone that needs to strong-name sign their application or library, and share internal classes with another projects via `InternalsVisibleTo` and the project where `InternalsVisibleTo` applies uses ClosedXML or references another library that does.

![image](https://user-images.githubusercontent.com/177608/100188578-deb5ff80-2ec0-11eb-8e88-b1e1989f6b28.png)

Because the assembly exposing internal types is signed, it requires that the library accessing the types to be signed as well (even though the main project doesn't reference it) and, of course, it cannot be signed because of ClosedXML being in the chain and not having a strong-name.

**Comment by Pankraty** [comment]
Wow, now it is way more clear. Looks convincing for me. 
Thanks for the effort of providing such a detailed explanation!
