### ISSUE TITLE
How to convert a Table to Range?

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#1559]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [x] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.95.3

**What is the current behavior?**
could not find anything in Wiki or Examples

**What is the expected behavior or new feature?**
[VBA ListObject.Unlist](https://docs.microsoft.com/en-us/office/vba/api/excel.listobject.unlist)

**Is this a regression from the previous version?**
No

**Comment by Pitterling** [comment]
that is what i try to achieve:
There is an exiting table and i want to convert it to a standard range ..

![image](https://user-images.githubusercontent.com/4181164/99322234-d41bba80-286f-11eb-8adf-da79909005d7.png)

**Comment by igitur** [comment]
This isn't possible at the moment.

**Comment by Pitterling** [comment]
Thx for the information ... so i change this to a "Feature Request" ?

What would be a workaround for the moment:

- copy table as IXLTable.AsRange()
- delete table and replace by range 

?

**Comment by Pankraty** [comment]
What exactly are you trying to achieve? If your goal is to delete the table but preserve the data then `ws.Tables.Remove(tableName);` should suffice. But if you want to preserve formatting too, this is currently not supported because ClosedXML only stores a table theme name (say, `"TableStyleMedium2"`) and a handful of flags, such as `ShowRowStripes` or `EmphasizeFirstColumn`, and does not know what styles are actually used for a particular theme.

If you are looking for a workaround that does not care about the _exact_ matching of styles but just need _some_ stylization similar to tables, you can go ahead with something like this:
```
    public static class XLTableExtensions
    {
        public static void Unlist(this IXLTable table)
        {
            table.Style
                .Border.SetOutsideBorder(XLBorderStyleValues.Thin)
                .Border.SetOutsideBorderColor(XLColor.FromTheme(XLThemeColor.Accent1, 0.4))
                .Font.SetFontColor(XLColor.FromTheme(XLThemeColor.Text1));

            for (int i = 1; i <= table.RowCount(); i++)
            {
                var row = table.Row(i);
                row.Style.Border.SetOutsideBorder(XLBorderStyleValues.Thin)
                    .Border.SetOutsideBorderColor(XLColor.FromTheme(XLThemeColor.Accent1, 0.4));

                if (table.ShowRowStripes && i % 2 == 0)
                {
                    row.Style
                        .Fill.SetPatternType(XLFillPatternValues.Solid)
                        .Fill.SetBackgroundColor(XLColor.FromTheme(XLThemeColor.Accent1, 0.8));
                }
                else
                    row.Style
                        .Fill.SetPatternType(XLFillPatternValues.None);
            }

            if (table.ShowHeaderRow)
            {
                table.FirstRow().Style
                    .Fill.SetPatternType(XLFillPatternValues.Solid)
                    .Fill.SetBackgroundColor(XLColor.FromTheme(XLThemeColor.Accent1))
                    .Font.SetFontColor(XLColor.FromTheme(XLThemeColor.Background1))
                    .Font.SetBold(true);
            }


            table.Worksheet.Tables.Remove(table.Name);
        }
    }
```
Note that this is a quick draft that does not consider alternating columns, total row, first / last column, etc. Feel free to extend the method according to your personal taste.

But if you don't mind to step the extra mile you can invest in PR defining built-in table styles (similar to what was done for sparkiline themes: https://github.com/ClosedXML/ClosedXML/blob/develop/ClosedXML/Excel/Sparkline/XLSparklineTheme.cs) and implement a complete version of the `Unlist` method that will take theme colors into account.

**Comment by Pitterling** [comment]
Thx Aleksei .. primarily i was looking for the VBA.Unlist functionality 
[https://docs.microsoft.com/en-us/office/vba/api/excel.listobject.unlist](https://docs.microsoft.com/en-us/office/vba/api/excel.listobject.unlist)

> Removes the list functionality from a ListObject object. After you use this method, the range of cells that made up the list will be a regular range of data.
> 
> Remarks
> Running this method leaves the cell data, formatting, and formulas on the worksheet. The Total row is also left intact. This method removes any link to a Microsoft SharePoint Foundation site. AutoFilter is also removed from the list.

Seems like Tables.Remove does the trick
