### ISSUE TITLE
Protection view in excel using c#

### ISSUE THREAD

**Issue by mscsesaamy** [ClosedXML/ClosedXML#1578]
[] In c# is that possible to open the excel without the protected view- be careful from the internet can contain virus,

**Comment by igitur** [comment]
Please complete full issue template, including code to reproduce.

**Comment by Nordfin** [comment]
![image](https://user-images.githubusercontent.com/65153974/104293052-dc822180-54bd-11eb-9b35-642be1d6cfe4.png)

I don't want that protected view when I download excel from the site, Is there any properties there to disable the option that I have attached the image above.

**Comment by mscsesaamy** [comment]
![image](https://user-images.githubusercontent.com/50664579/104294079-0be55e00-54bf-11eb-88cf-244971188304.png)

I don't want that protected view when I download excel from the site, Is there any properties there to disable the option that I have attached the image above.

**Comment by igitur** [comment]
I'm not aware of any property to set, but if you can provide me with 2 almost identical files where 1 is protected and the other is not protected, then I can compare the internals. Else you'll have to take this up with the OpenXML SDK team at https://github.com/OfficeDev/Open-XML-SDK. ClosedXML is just a wrapper around OpenXML.

I'll reopen if necessary.

**Comment by Pankraty** [comment]
This issue is not related to ClosedXML. Basically every modern browser adds a special attribute to files that were downloaded from the web and then Excel treats such files with special precautions. You can do a little experiment yourself:
1. Create a workbook in Excel
2. Upload it to (for example) Github
3. Download it back
4. Open it in Excel - you'll see this Protection View warning.

Files are identical, obviously, but their NTFS attributes differ:
![изображение](https://user-images.githubusercontent.com/19576939/104845855-0a69ca80-58f1-11eb-94d7-700b5d82c96d.png) ![изображение](https://user-images.githubusercontent.com/19576939/104845863-1190d880-58f1-11eb-934d-6df17554db40.png)

The maximum you can do - is to turn off protected view for files from the Internet in Excel Trust Center. But do this at your own risk!
![изображение](https://user-images.githubusercontent.com/19576939/104845943-6a607100-58f1-11eb-89fc-c7d649faf18b.png)
