### ISSUE TITLE
Cannot set DataType for cells where value doesn't match specified DataType

### ISSUE THREAD

**Issue by zdiomaz** [ClosedXML/ClosedXML#1673]
[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/6571170/sample.xlsx)
## Read and complete the full issue template

It is possible in Excel to set DataType as Number for column even if values do not match specified DataType. And setting value which is match specified DataType cause format display value same as other in this column.
But while setting DataType using ClosedXML it cause error "Cannot set data type to Number because '<value>' is not recognized as a number."
It is need to check value of each cell to make ability set DataType without error and only to cells with matched value.
It wil be great to have ability set DataType regardless cell value.
I think it will be useful not only for Number DataType but other supported DataTypes also.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

ArgumentException - "Cannot set data type to Number because '<value>' is not recognized as a number."

**What is the expected behavior or new feature?**

DataType set without failing regardless cell value

## Reproducibility
**Code to reproduce problem:**
```c#
string path = @"sample.xlsx";

var workbook = new XLWorkbook(path);
var worksheet = workbook.Worksheet("Sheet1");
worksheet.Columns(1, 1).SetDataType(XLDataType.Number);

workbook.SaveAs("D:\\output.xlsx", false);

```

- [x] I attached a sample spreadsheet.
[sample.xlsx](https://github.com/ClosedXML/ClosedXML/files/6571177/sample.xlsx)

**Comment by igitur** [comment]
The exception that I get, is: `Unhandled exception. System.ArgumentException: Cannot set data type to Number because 'Number' is not recognized as a number. (Parameter 'value')`

And this is correct. You can't set A1's data type to `Number` because its value is `"Number"`, which is text.

**Comment by diomaz** [comment]
Yes, I know. But when you try to set DataType as Number in Microsoft Excel - it allows to do that without errors. Why we can't do this in ClosedXML?

**Comment by igitur** [comment]
What you see in Excel is the number format, which, in ClosedXML, is accessible via `cell.Style.NumberFormat`.

`DataType` is a property that's much more closer tied to the cell's value. You can't edit this in Excel directly, but we expose it.

What do you want to achieve? Just change the text values that look like numbers to actual numbers?

**Comment by diomaz** [comment]
![image](https://user-images.githubusercontent.com/5476410/120305556-8e898100-c2d9-11eb-8292-c2cf7ea59d73.png)
I think this is an equivalent for cell.DataType property in ClosedXML. And cell.Style.NumberFormat is another property and means how to display stored value (decimal separator, decimal places etc). 
I want to achive setting DataType for column entire, not for every cell with checking every value. And in Excel I want to set numeric value and it must treat as numeriс with appropriate formatting according to regional settings.

**Comment by igitur** [comment]
> ![image](https://user-images.githubusercontent.com/5476410/120305556-8e898100-c2d9-11eb-8292-c2cf7ea59d73.png)
> I think this is an equivalent for cell.DataType property in ClosedXML. 

It's not equivalent. What you see there is the Style.NumberFormat. Excel even says the same when you hover over that dropdown.

![image](https://user-images.githubusercontent.com/145854/120309783-ecb46500-c2d5-11eb-956c-a5d10e80363e.png)

> I want to achive setting DataType for column entire, not for every cell with checking every value. And in Excel I want to set numeric value and it must treat as numeriс with appropriate formatting according to regional settings.

This isn't currently possible, but I can imagine it's a popular use-case, so I will look into adding a utility method.

For now, you have to identify manually the cells that look like numbers and set their data type.

By the way, when you set your column to `Number` in Excel, does it actually change those cells? I'm under the impression that those cells with text values will remain as is.

**Comment by diomaz** [comment]
> For now, you have to identify manually the cells that look like numbers and set their data type.

According to source code while setting DataType to Number performs [parsing to Double](https://github.com/ClosedXML/ClosedXML/blob/ce7fb695a70d2e870078db4efe143a9e90ac7ad2/ClosedXML/Excel/Cells/XLCell.cs#L592). Even if I manualy check every cell for number where is the guarantee that i did it right? My code checks for a number, SetDataType() checks for a number - similar operation is performing twice and the result each of them maybe different due to regional/culture settings (at least) - which also may cause error. I don't want to perform value check twice.
Probably it would be useful parametrize SetDataType() method with bool argument (or by any other clear way), which point: throw exception or not in case of inappropriate Data Type - this would alow avoid double value check and worring about actual value.

**Comment by igitur** [comment]
Yes, that sound kind of like the utility method I had in mind.

**Comment by flynnpat** [comment]
+1

I'm creating Excel files to be consumed by an application which checks the data types of the column headings despite those cells obviously containing column heading text rather than dates etc.  - I can't fulfill this with ClosedXML currently. @diomaz

**Comment by igitur** [comment]
@flynnpat I think you're confusing numeric format with data type. See previous discussion in this thread.

**Comment by jahav** [comment]
`IXLCell.DataType` setter has been removed in 0.100. Cell now actually stores value as a typed value instead of guessing from `DataType` property and a string value. Closing this issue because it no longer makes sense.

If user needs to convert cell value from one type to another, it must be done by user. ClosedXML no longer does any magical conversion. It's users job to define conversion (e.g. should "1.25" convert to 1.25? What if locale has a different decimal point? And so on). The type of a cell in Excel can be determined by function `TYPE`.

Is user only needs to change how the cell value is formatted (that is what the dropdown in Excel is for) in Excel/what ClosedXML returns in `IXLCell.GetFormattedString()`, use [Number format API](https://docs.closedxml.io/en/latest/features/cell-format.html#number-format). Note: Changing the formatting never changes actual value.
