### ISSUE TITLE
Can let XLCellsUsedOptions  to "public" 

### ISSUE THREAD

**Issue by MightLin** [ClosedXML/ClosedXML#1691]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.95.4

**What is the current behavior?**

I want to copy a cell or row, and I only need copy value or style

**What is the expected behavior or new feature?**

Why can't let `XLCellsUsedOptions ` is public

**Is this a regression from the previous version?**

no

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#

//  I need this 
r.FirstCell().CopyFrom(row.FirstCell(), XLCellCopyOptions.Style);

```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
I am closing this, because I don't want to introduce another API at this time.

Each API is a additional burden and constraint to limited time maintainers can invest into the project. It is a promise that it is going to work, not break in new versions, be documented, and behave in a performant manner.

For better or worse, a significant portion of current API doesn't satisfy all these conditions. Adding another would just make it worse.
