### ISSUE TITLE
Header/Footer length error - xlsx file

### ISSUE THREAD

**Issue by MisoMi** [ClosedXML/ClosedXML#174]
I try open existing xlsx file (created by MS Excel) in csharp and I using ClosedXML and OpenXML library. The _first sheet have header created by MS Excel._

1. If I open xlsx file first time, all is ok. I add new worksheet, and set some cells values, styles, save it. 
2. Second times, is ok too. If I try only open file, not adding any data ... 
3. If I try open this file, for example, for the third time, Is there problem. 

I get error message: **Headers and Footers cannot be longer than 255 characters (including style markups).** 

If I call clear method after I add new sheet and save file 

> PageSetup.Header.Clear()

new sheet is added properly and the file OK

**Comment by igitur** [comment]
Can you remove sensitive information from the file and the file to this issue?

**Comment by MisoMi** [comment]
Yes, I sendig this file in attachment.

2017-02-02 12:22 GMT+01:00 Francois Botha <notifications@github.com>:

**Comment by igitur** [comment]
@MisoMi Go to https://github.com/ClosedXML/ClosedXML/issues/174 in your browser and upload the file there. Attachments don't work on email replies to Github issues.

**Comment by MisoMi** [comment]
Ok

[test_F.xlsx](https://github.com/ClosedXML/ClosedXML/files/754288/test_F.xlsx)

**Comment by igitur** [comment]
The PR has been merged into the `develop` branch. I'd appreciate it if you could pull the `develop` branch and check that it solves your issue. Thanks.

**Comment by Muschti** [comment]
a while ago since my last post but i think we were able to identify the same header/footer error of Excel. Exact same behavior as described from MisoMi. 2 times i'm able to "paste" a data table in Excel, the 3rd time it crashes during the "save" command. opening Excel, drill down to the footer, open the right "footer cell", hit enter, leave, save and close Excel. after this steps, you have another 2 attemps to fill data until it becomes impossible again. 

if i understand it correct, this bug has been solved and merged in the develop branch. can you provide me a "preview" dll from the develop branch please? or is it already in the version 0.87? i currently use version 0.85. i would like to implement it and test in my project. of course i would post here my findings to confirm the fix - i hope this helps you to close this bug report. unfortunately i'm not talented enough to download the develop branch and find/build the dll myself :-) - sorry for this and thx in advance

**Comment by igitur** [comment]
@Muschti Please try [v0.88-beta1](https://www.nuget.org/packages/ClosedXML/0.88.0-beta1) from NuGet, else log a new issue with proper code sample (as described in the issue template) .

**Comment by Muschti** [comment]
Thx, was not able to find the link....i will test asap and let you know

**Comment by Muschti** [comment]
@igitur I was testing quite a lot of things and was not able to reproduce this problem again with 0.88 beta. in my opinion this bug is fixed. otherwise i will open a new issue. 
many thanks
