### ISSUE TITLE
Cell Values like "3-3.5" or "4-4.5" implicitly sets data type to DateTime and there's no way to assign it as a string

### ISSUE THREAD

**Issue by vcartera81** [ClosedXML/ClosedXML#1747]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

Setting cell Value to "3-3.5" or "4-4.5" and data type to Text will render cell as DateTime 3 march 2005 or 4 april 2004. There's no way to fill in the cell with just "3-3.5" value.

**What is the expected behavior or new feature?**

When setting Cell data type to Text and Value of the cell is "3-3.5" should set the cell value to "3-3.5"

**Code to reproduce problem:**
```c#
public void Main()
{
    var worksheet = workbook.Worksheets.Add("Sample Sheet");
    worksheet.Cell("A1").DataType = XLDataType.Text;
    worksheet.Cell("A1").Value = "3-3.5";

    workbook.SaveAs("HelloWorld.xlsx");
}
```

**Comment by jahav** [comment]
The heuristic for determining the data type from a string or other values has been removed in #1894. The value and type are now intrinsically connected. The value of a cell has been limited to Excel types (+DateTime and TimeSpan, but that is basically a number masquerading as a different type). The type that is passed to the cell is the type cell will have, no mis-representation due to fuzzy logic anymore.
