### ISSUE TITLE
Cell does not wrap text if contents is a formula.

### ISSUE THREAD

**Issue by DSA-System** [ClosedXML/ClosedXML#1833]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**
0.96

**What is the current behavior?**

When calling wraptext on a cell with a formula, the cell contents do not wrap, and text is cut off

**What is the expected behavior or new feature?**

Text should wrap in a similar fashion to if it was simple text.

**Is this a regression from the previous version?**

No

## Reproducibility
**Code to reproduce problem:**
```c#
public void Main()
{
            XLWorkbook xLWorkbook = new XLWorkbook();
            IXLWorksheet xLWorksheet = xLWorkbook.AddWorksheet("Sheet1");
            xLWorksheet.Cell(1, 2).FormulaA1 = "=CONCATENATE(\"hello\", \"there\", \"good\", \"sir\")";
            xLWorksheet.Cell(1, 2).Style.Alignment.SetWrapText(true);
            xLWorkbook.SaveAs("Test.xlsx");
}
```

[Test.xlsx](https://github.com/ClosedXML/ClosedXML/files/9059974/Test.xlsx)

Is this expected behavior? Am I missing something obvious?

**Comment by jahav** [comment]
You have probably moved on, but you weren't missing anything obvious. The problem was that the cell with the formulas don't save evaluated values by default. Excel thus has to calculate the value first and it is probably later in the pipeline than "get min height for wrapped cell values."

To save values of formulas, you have to set the (very intuitively named) `EvaluateFormulasBeforeSaving` options:
```
var xLWorkbook = new XLWorkbook();
var xLWorksheet = xLWorkbook.AddWorksheet("Sheet1");
xLWorksheet.Cell(1, 2).FormulaA1 = "=CONCATENATE(\"hello\", \"there\", \"good\", \"sir\")";
xLWorksheet.Cell(1, 2).Style.Alignment.SetWrapText(true);
xLWorkbook.SaveAs("Test.xlsx", new SaveOptions { EvaluateFormulasBeforeSaving = true });
```

I have added a note to documentation: https://closedxml.readthedocs.io/en/latest/features/functions.html

This can be solved by calculating the values which is not feasible at this time, but I made a ticket for it #1926

**Comment by DSA-System** [comment]
Thank you! I have moved on, but your response very much appreciated.
