### ISSUE TITLE
SaveAs stream over 25k rows performance issue

### ISSUE THREAD

**Issue by fguinther1** [ClosedXML/ClosedXML#1838]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [X ] Question

**Did you test against the latest CI build?**
- [X ] Yes - 0.96.0

**What is the current behavior?**

taking a long time to save as stream ( load testing 50k rows with 245 columns as max and then going down to 25k rows 245 columns, etc ) - on average it's taking 40 sec to save in order for me to download the excel file.  Taking at least 1.5 min with 50k rows 245 columns with some random style formatting ( background colors, font colors, border colors )

Also, it seems like using the "set all borders" is much slower than setting individual borders ( e.g. top, right, bottom, left ) - do you know why?

**What is the expected behavior or new feature?**
Expected to take less than 30 sec to save and download the file

**Is this a regression from the previous version?**

No

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**

see attached zip file for code sample and spreadsheet

- [ X] I attached a sample spreadsheet.  (You can drag files on to this issue)
[sample_code.zip](https://github.com/ClosedXML/ClosedXML/files/9135548/sample_code.zip)

**Comment by jafin** [comment]
If you remove the custom styles, does performance improve?  I was doing some work on performance, and noted the styling takes a heavy hit on performance and gets exponentially worse based on cell count.  I have a branch up with some work I've been doing to attempt to improve both performance and memory consumption.

I can't run your code fragment, but would be interested if you can run the branch code and notice any performance changes? (https://github.com/jafin/ClosedXML/tree/wip/performance-memory)

Differences from 0.96 that I recall:
* Minimum framework is net462/netstandard 2.0
* Interfaces on structs are removed, the structs are now public and required to be used (avoids excess memory usage from struct cloning from the interface). This is a breaking change. So if you used ICell swap to to Cell
* Some other internal changes that *may* have an impact on existing 0.96 code, I need to document.

I'd like to do a PR for this repo, but I need to tidy stuff up first and document changes better

I observed a lot of time is spent in conditional formatting
![image](https://user-images.githubusercontent.com/127927/180907502-a6050648-d003-4504-8ec7-67944d4559d8.png)

Here are the stats for the report I was having issues with:

#### Existing 0.96 code

|     Method |    Mean |   Error |  StdDev |  StdErr |     Min |      Q1 |  Median |      Q3 |     Max |   Op/s |
|----------- |--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|--------:|-------:|
| RenderTest | 37.82 s | 14.22 s | 0.780 s | 0.450 s | 36.94 s | 37.52 s | 38.10 s | 38.26 s | 38.42 s | 0.0264 |


#### And results from Branch code

|     Method |    Mean |   Error |   StdDev |   StdErr |     Min |      Q1 |  Median |      Q3 |     Max |   Op/s |       Gen 0 |       Gen 1 |     Gen 2 | Allocated |
|----------- |--------:|--------:|---------:|---------:|--------:|--------:|--------:|--------:|--------:|-------:|------------:|------------:|----------:|----------:|
| RenderTest | 7.454 s | 2.179 s | 0.1194 s | 0.0690 s | 7.371 s | 7.386 s | 7.401 s | 7.496 s | 7.591 s | 0.1342 | 311000.0000 | 103000.0000 | 5000.0000 |      5 GB |

It will take ~38s from 0.96 version, and around ~7.5s from my branch. (a modest improvement)

**Comment by fguinther1** [comment]
Hi Jason,

Thanks for the reply! I really appreciate it.  Looks like some promising results!  I will need to check out this branch and run some tests.

**Comment by PaulEthertonDP** [comment]
Has anything gone anywhere on this since the summer?

I noticed some massive performance impact from `.SetDataType` - and there were a very large number of GCs in the Visual Studio Diagnostic Tools.

So anecdotally, I suspect that
> Interfaces on structs are removed, the structs are now public and required to be used (avoids excess memory usage from struct cloning from the interface). This is a breaking change. So if you used ICell swap to to Cell

is a good analysis.

In my specific case, simply removing `.SetDataType` in a few places has sped up my spreadsheet generation from over a minute to a couple of seconds...

**Comment by fguinther1** [comment]
Hi, thanks for reaching out.

I haven't worked on this in a while ( probably since summer ) - but the create workbook wasn't really the issue ( as long we kept the individual cell over-rides to a minimum ) - the performance issue was saving as memory stream, it took well over 30s just to save it.  I was able to pinpoint that as the root cause.

workbook.SaveAs(memoryStream);

**Comment by PaulEthertonDP** [comment]
Thanks for the reply - It sounds like my issue is something distinct then.

If I find the time, maybe I'll raise it as a separate issue with all the necessary detail.

**Comment by fguinther1** [comment]
Yeah for sure, I appreciate the follow up as well.

I think the load test we were doing was 245 columns with 100k rows.  We have some pretty intense reports that we need to export and they can get quite large.

Again, creating the workbook was fine - it was just saving it.

Thanks

**Comment by jahav** [comment]
@fguinther1 Do you still have a reproducible sample? The code you posted is missing data creation, it is just a code of `ExcelService` with some translation logic. I tried to generate some data for it, but the end result was just half of time for workbook creation, half for for saving. The trace you posted had 33% of time in conditional formatting.

Basically I wonder if this issue if for "saving just data is still horribly" or "conditional formatting is horribly slow too". Granted, both are likely true.

**Comment by fguinther1** [comment]
I think the last performance I ran was even a trimmed down version - logic just in the API controller (no models or service layer like in the code sample I sent)


        private DataTable GetTable()
        {
            DataTable table = new DataTable();

            // add columns
            for (var col = 1; col <= 245; col++)
            {
                table.Columns.Add("col_" + col.ToString(), typeof(string));
            }

            List<string> valuesList = new List<String>();
            foreach (DataColumn dc in table.Columns)
            {
                valuesList.Add("testing 101.001000000000 test");
            }

            for (var row = 1; row <= 50000; row++)
            {
                table.Rows.Add(valuesList.ToArray<string>());
            }

            return table;
        }

public IActionResult TestExcel()
        {

            var table = GetTable();


            var stopwatch = Stopwatch.StartNew();


            XLWorkbook workbook = new XLWorkbook(XLEventTracking.Disabled);


            var worksheet = workbook.Worksheets.Add("fgtesting");

            worksheet.Cell(1,1).InsertData(table);

            // average 1.06min 245 columns 50k rows (no styles)
            var memoryStream = new MemoryStream();

            workbook.SaveAs(memoryStream);

            using (System.IO.StreamWriter writetext = new System.IO.StreamWriter("ClosedXMLperformancetest.txt"))
            {
                writetext.WriteLine("create and save workbook\nelasped time = " + stopwatch.Elapsed);
            }


            workbook.Dispose();


            GC.Collect();
            GC.WaitForPendingFinalizers();
            GC.Collect();

            return File(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "testingExcelClosedXML.xlsx");

            //return Ok("testing excel");
        }

**Comment by jahav** [comment]
I checked out the sample and it is the "saving cell values is slow." I am declaring this to be the ticket for "Saving worksheets with a lot of cell values is slow".

# Design
Basically continue the work on foundation made by #1874. The `SheetData` element is saved by saving each row DOM into the stream. That saves memory, but it still incurs penalty of allocating and building DOM (see the image below for some places ), just piece by piece. By writing individual elements and attributes, there won't be a need to build and allocate DOM.

In order to hand-write `SheetData` and it's descendants, make a custom [OpenXmlWriter](https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml.Framework/OpenXmlWriter.cs), instead of currently used  [OpenXmlPartWriter](https://github.com/OfficeDev/Open-XML-SDK/blob/main/src/DocumentFormat.OpenXml.Framework/OpenXmlPartWriter.cs) (through `OpenXmlWriter.Create`). Try to use more performant writer (maybe [LightXmlWriter](https://github.com/lechu445/LightXmlWriter) instead of `XmlWriter`).

![1838-dotTrace](https://user-images.githubusercontent.com/7634052/209410982-6b67a21e-3523-4b26-84a2-efa5d7910317.png)

# Prerequisites
Full streaming option would require that ClosedXML can represent all attributes of `SheetData` and it's descendants. That is pretty much only used when modifying existing file (=ClosedXML representation is merged with the original DOM to keep unknown elements from the original workbook and ). Probably best option is to load all to the ClosedXML structures and just ignore merging for `SheetData` element. It would be pretty hard to optimize without full control. ClosedXMl doesn't have to do anything with it, just load and store. By skimming through xsd, it is mostly array/table formulas (should be done in #815) and some not-so-freqent usages (e.g. show phonetics, i.e. furgana for japanese or link to OLAP metadata), seems doable.

#815 is a definitive prerequisite, but explore custom open xml writer impact even before that (without modification of existing file, we don't really need all the other stuff).

**Comment by MorgeMoensch** [comment]
I'm hitting the same issue with `.SaveAs(stream)` being the bottleneck. 

I've got a database table with 200'000 rows and 34 columns I need to export to an XLSX. (And bigger ones to process in the future as well).

For this specifix example, I measured that inserting the data with `.InsertData()` takes about 7'000ms and saving it 30'600 ms. The Values were measured with System.Diagnostics.Stopwatch in .NET 6.

**Comment by vbjay** [comment]
Just a thought. Exporting to excel that many records, might want to look at non excel solutions. Power bi, reporting services, maybe tweak sql to have database server generate calculated values in query.  Maybe make a solution using R or other solution to pull the needed stuff.

**Comment by MorgeMoensch** [comment]
Thanks for the input @vbjay!

Yeah, I don't like how it is either. However, due to some business requirements those are no viable options. We used to export CSVs which the people could open with excel, but one can't put AIP-Labels (Azure Information Protection) on them - which is why this is no longer accepted. I don't want to hijack this topic, but do you know of a solution to kind of pipe a CSV into an XLSX, similar to what excel does when it opens a CSV?

**Comment by vbjay** [comment]
Start a discussion on it in this repos discussions and @ me.

**Comment by jahav** [comment]
I have modified saving so it uses XmlWriter for streaming in #1984 (mostly, still need to fix copy xml code from `OpenXmlPartWriter` to `XmlWriter`). It should be about twice as fast as originally. I consider it good enough for now (it's ~600 MB of XML) and have closed the issue.

I haven't made a benchmark, but I did run it a few times with the code from @fguinther1 
 (see https://gist.github.com/jahav/3c1432ebae08545debc2e1c4b7a20cf6 ).

The saving part to memory should be slightly more than twice as fast. I did try it on more diverse data types than just text and wrote data to a filesystem. The results were also roughly twice as fast.

| SaveAs to MemoryStream | 0.100.3  | 0.101.0-preview |
| ------------- | ------------- |----|
| net48 - 1st run | 46.99 | 21.13 |
| net48 - 2nd run | 45.32 | 20.83 |
| net48 - 3rd run | 45.44 | 20.92 |
| net6 - 1st run | 37.79 |  20.26|
| net6 - 2nd run | 36.69 |  16.83|
| net6 - 3rd run | 36.69 | 16.37 |

The dotTrace basically says that we spend most of time in writing XML (see lower bar, with number 65%). It's 97% for just `WriteCellValue` and `<StreamSheetData>g__WriteStartCell`. `Dispose` is the zip compression, nothing I can do with that for now.

![image](https://user-images.githubusercontent.com/7634052/214730859-2f8f6adc-5c4d-4b55-8bf8-d23c802844f9.png)

There are few things that could be done, but this is good enough for now. At 10s of millions of cells, the memory consumption is the main problem (hopefully #1969 will be significant improvements, pending proof-of-concept results). 

Things that could be done:
* don't write default style index (0) to cells - ClosedXML writes all values, even the default one. Need to fix all test files after change.
* don't write span attribute for cells - that is just optimization for Excel. Excel probably had literally decade-years of time spent to optimize loading and saving, it can manage. Need to fix all test files after change.
* use parallelism - each chunk of rows would be pre-written to a buffer and the buffer would then be written just as a stream of bytes. Not doing any parallelism before #1926.
* try to use LightXmlWriter (basically a wrapper over `TextWriter`) or perhaps `XmlWriter.WriteRaw` to get more performance by skipping all XML validity checks and escaping.
