### ISSUE TITLE
Delete doesn't scale and the performance is terrible on large files

### ISSUE THREAD

**Issue by michaelgorman** [ClosedXML/ClosedXML#1863]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [X ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.1

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/7871709/191057048-1cd340eb-f03f-41cc-a95e-f6c60692fac8.png)

**What is the expected behavior or new feature?**

Complete this.

**Is this a regression from the previous version?**

Regressions get higher priority. Test against the latest build of the previous minor version. For example, if you experience a problem on v0.95.3, check whether it the problem occurred in v0.94.2 too. 

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
                  foreach (var r in worksheet.Range("A" + dataTagFirstRow, "A" + dataTagEndRow).Rows())
                  {
                     worksheet.Row(r.RowNumber()).Delete();
                  }
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
Please don't delete individually each row. Create a range and call a delete method, e.g.

`ws.Range($"A1:A{num}").Delete(XLShiftDeletedCells.ShiftCellsUp);`

See wiki https://github.com/ClosedXML/ClosedXML/wiki/Deleting-Ranges

If you delete a row, ClosedXML has to do housekeeping each time a row is deleted and unfortunately it scales with a number of ranges (each time worksheet.Row(number) is called, a new range is created (if it didn't already exist because of some cell with value) that has to be housekeeped).

We should definitely do a better housekeeping, but at this moment, it is O(n^2) for deleting rows .

**Comment by michaelgorman** [comment]
I did look at the wiki, but I need to delete a whole row because I have sets of data that are jagged on the same page, deleting by range will corrupt the other sets. Does deleting by a range still do the same house keeping just on a smaller set of cells?  I do have a cap of 256 cols which I could set as the range but deleting all those cells might be just as inefficient, I will have  to try it. I did try to find the max col used for the entire sheet but I think it was unreliable as well and didnt always find the max col.

**Comment by jahav** [comment]
If you need to delete a whole row, use full row reference (like `5:10` fifth row to tenth row) or just specify a cell of first column to the very last column (A1:XFD1000).  

`ws.Range($"1:{num}").Delete(XLShiftDeletedCells.ShiftCellsUp);`

I am reasonablt sure we housekeep only existing cells and shouldn't be a penatly for bigger range (i.e. full row).

**Comment by jahav** [comment]
I assume it worked as needed. I have added a link to the performance guide to the front page of wiki with an explanation and a comment about poor performance to the `Delete` methods on `IXLRow` and `IXLColumn`.

I am closing the issue, because the O(n^2) complexity is just pretty much inherent to the loop solution and loop is wrong approach and range API is a reasonable solution. 

When I run a dotTrace on a loop, a property getter was called tens of millions of times and took up a second or two, that is just wrong.
![image](https://user-images.githubusercontent.com/7634052/191862577-eb669715-2033-49c1-adb2-0628aa89cc15.png)

**Comment by michaelgorman** [comment]
I did try your suggestions and it was still to slow, i have no choice but
to try openxml or go back to com for this operation
