### ISSUE TITLE
Default nuget install fails with missing dependency "SixLabors.Fonts"

### ISSUE THREAD

**Issue by dfourmanfsquared** [ClosedXML/ClosedXML#1883]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [ ] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.0

**What is the current behavior?**

Attempting to install ClosedXML in a new .net 4.8 project from nuget results in the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Unable to resolve dependency 'SixLabors.Fonts'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'.				

**What is the expected behavior or new feature?**

Installing CloseXML from nuget should complete successfully

**Is this a regression from the previous version?**

Yes - Version 0.96.0 installs correctly

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

1. Create a new project
2. Assign it to .net framework 4.8
3. Attempt to install the latest CloseXML version from nuget
4. It should fail

**Code to reproduce problem:**

N/A - nuget error not code error

**Comment by jahav** [comment]
It seems `package.config` nuget resolution ignores prerelease package during dependency resolution. 

To be honest, I won't to invest my time into this, because:
* I don't think I can do anything about it (other than forking the library and making my package that doesn't have betaXY suffixes)
* It only affects a `package.config` nuget resolution (at least it seems so - I am surprised that the template still uses this obsolete method). The `dotnet add package` works as expected (for SDK style projects)
* should resolve itself if SixLabors.Fonts ever release 1.0 version.
* there are several really easy workarounds. 

There is a dearth of maintained managed font libraries (that is why dependency on prerelease), so until `SixLabors.Fonts` has a stable release, use one of workarounds:

# Use PackageReference
Migrate from `package.config` to `PackageReference`. `package.config` has been deprecated for 5 year already and there is a full-fledged replacement that is better in every way that works on .NET Framework 4x. If you use PackageReference, package is installed without a problem (well, restored at least).

See [Migrate from packages.config to PackageReference](https://learn.microsoft.com/en-us/nuget/consume-packages/migrate-packages-config-to-package-reference)] and related pages.

# Install first package 
Install SixLabors.Fonts-beta18 package and then install ClosedXML package. That worked for me even for `package.config` nuget restore.

# Install through Package Manager Console
Open the Package Manager Console and specify the `-IncludePrerelease` parameter during installation.
> Install-Package ClosedXML -Version 0.97.0 -Verbose -IncludePrerelease

**Comment by RvdHout** [comment]
.NET Framework 4.0 and .NET Framework 4.6 silently dropped?

**Comment by jahav** [comment]
> .NET Framework 4.0 and .NET Framework 4.6 silently dropped?

Yes, only platforms supporting netstandard 2.0 are supported, i.e. net462 is the earliest with full net standard 2.0 support (net461 might work too, though net standard 2.0 support is not complete).

See https://github.com/ClosedXML/ClosedXML/pull/1836#issuecomment-1183835164

**Comment by MissyGH** [comment]
I wanted to comment that I encountered this issue on v 0.100.3 and installing through the package manager worked.
