### ISSUE TITLE
Is possible improve the initialize/read time with some parameters?

### ISSUE THREAD

**Issue by elfasito** [ClosedXML/ClosedXML#1910]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [X] Question

**Did you test against the latest CI build?**
- [X] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.97.1-preview

**What is the current behavior?**

Initialize a new empty workbook and add a sheet, takes around of 5 seconds on android.
```
 using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Sample Sheet");
            }
```
Initialize and read a small workbook (around of 100 cells), takes around of 20+ seconds on android

On windows takes around of 1,5 seconds to initialize a empty workbook and around 5 seconds to initialize and read the same 100 cells sheet.
(the hardware performance has no comparison)

**What is the expected behavior or new feature?**

improve initialization time on android 

**Is this a regression from the previous version?**

NO

## Reproducibility

Any build

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

Hello, is there some parameters what I can set to improve the performance at initializing?
Im just filling a preformated excel workbook with simple text, no colors, font size, etc.

**Comment by jahav** [comment]
There are no parameters to improve the startup time, sorry.

Most of the time is likely loading assemblies and JITing code (e.g. setting a auto-property/adding a single item to a collection takes up 6ms... no way). Cold start and all. In my case, first start was 1.3 second against 2nd start with 250ms.

A lot of time is spent on regex compilation (110ms in a quick trace). I checked what happens If I remove `RegexOptions.Compiled` flag and it was limited (~20-30ms). NET7 is [preparing some nice  source generators](https://devblogs.microsoft.com/dotnet/regular-expression-improvements-in-dotnet-7/#source-generation) for regexp, but ClosedXML will stay on NET standard 2.0 for a long time... 

Profiler out of the code you posted.
![image](https://user-images.githubusercontent.com/7634052/200205494-3543b010-0212-4734-aed6-0acad7dea9a0.png)
