### ISSUE TITLE
Save version-dependent functions with _xlfn prefix

### ISSUE THREAD

**Issue by pratikthorat** [ClosedXML/ClosedXML#1915]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.95.4

**What is the current behavior?**

When we generate the excel with `concat` formula in it, and then if we try to open the excel in Microsoft Excel the generated excel shows formula error because the formula gets prepended with @ symbol `@CONCAT`.

Note - Same sheet works fine in google spreadsheet. And also if I remove the @ symbol from `@CONCAT` formula in the generated excel it works fine in Microsoft excel as well

Code - `worksheet.Cell(3,4).FormulaA1 = "=CONCAT(COUNTBLANK(D4:D21))"`

![IMG_8B8724942285-1](https://user-images.githubusercontent.com/8032832/202360651-077d3f2b-c165-41a1-bfec-43b10e566f53.jpeg)

**What is the expected behavior or new feature?**
The CONCAT formula should work in google spreadsheet as well as microsoft office

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

**Code to reproduce problem:**
```c#
public void Main()
{
            using (var workbook = new XLWorkbook(templateFilePath))
            {
                if (!workbook.TryGetWorksheet("your sheet name", out var worksheet))
                {
                    throw new Exception("Passed worksheet name is not found in excel template.");
                }

                 worksheet.Cell(3,4).FormulaA1 = "=CONCAT(COUNTBLANK(D4:D21))";

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var updatedFileBytes = stream.ToArray();
                    var updatedFileBase64 = Convert.ToBase64String(updatedFileBytes);
                    return updatedFileBase64;
                }
            }
}
```

**Comment by jahav** [comment]
@pratikthorat Please try to use `_xlfn.CONCAT` instead of CONCAT or use CONCATENATE function.

```csharp
ws.Cell(3, 4).FormulaA1 = "=_xlfn.CONCAT(COUNTBLANK(D4:D21))";
```

Newly added functions generally have prefix `_xlfn`, so old Excel that doesn't support it knows that they are something from newer version of Excel (they even have [a list of likely future functions](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/5d1b6d44-6fc1-4ecd-8fef-0b27406cc2bf)).
The prefix is hidden in Excel, you will only see CONCAT.

The `@` sign is an operator for implicit intersection. Up to Excel 2019, there wasn't any operator for implicit intersection, it was done automatically. With addition of dynamic arrays, implicit intersection has to be specifed, otherwise data will spill to other cells, so new Excel automatically adds the implicit intersection operator `@` to some functions... not sure why in this case

**Comment by jahav** [comment]
I am closing this issue in favor of #1926. In order to properly do this, formula must be converted to abstract syntax tree and serialized back to string form. It would be trivial if I had AST, but I don't. ClosedXML currently doesn't do that (well, there is a "cache" of formulas, but less said about it the better) at the moment because
* Performance
* Parser doesn't support some pretty important features (e.g. structured references for table formulas)

In the meantime, I have added a note to the documentation about a need to add a prefix along with functions that require the prefix: thathttps://closedxml.readthedocs.io/en/latest/features/functions.html
