### ISSUE TITLE
UAC problem on Windows platform when AdjustToContents() is called

### ISSUE THREAD

**Issue by craftsmansam** [ClosedXML/ClosedXML#1949]
**Do you want to request a *feature* or report a *bug*?**
- [] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**
.97

**What is the current behavior?**

With the use of SixLabors.Fonts, UAC must be turned off on Windows to call AdjustToContent().  Maybe this is acceptable for the ClosedXML project, but to me, turning UAC off 

With UAC on, it'll throw a System.ArgumentException: Unable to find font Calibri or fallback font Microsoft Sans Serif. Install missing fonts or specify a different fallback font through 'LoadOptions.DefaultGraphicEngine = new DefaultGraphicEngine("Fallback font name")'.

With UAC turned off, it'll work as expected.

This is a problem in the SixLabors.Fonts package, as it is trying to enumerate the Windows\Fonts directory, which requires UAC to be turned off.

**What is the expected behavior or new feature?**

Turning UAC off shouldn't be necessary for ClosedXML to function.

**Is this a regression from the previous version?**

UAC was not a problem in prior versions of ClosedXML

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Turn UAC on
Call AdjustToContents()

**Comment by jahav** [comment]
ClosedXML can't determine text size without a font. Font files contains font metrics and all other stuff required for determining a dimensions of a text. It can't magically determine font metrics and substitution tables out of thin air.

Calling `AdjustToContents` and not providing font metrics will fail, because dependency hasn't been provided. 

You need to 
* set `IXLColumn.Width`/`IXLRow.Height` yourself.
* wait for 0.100 and bundle font https://closedxml.readthedocs.io/en/latest/tips/missing-font.html#bundle-font-version-0-100

Could you please be more specific on how is the UAC set to block access to font directory? Quick googling hasn't found anything.

**Comment by Roofy5** [comment]
Hi guys,
I have exactly same issue as @craftsmansam so this is real bug.
When I deleted `AdjustToContents` method call, it started working fine.

**Comment by jahav** [comment]
@Roofy5 Could you please give me a reproduction for UAC? I am not familiar with it and have no idea how to repro it. There are hundreds of options what to disable, what to enable...

**Comment by jahav** [comment]
Closing due to lack of reproduction scenario in the issue and pretty simple principle for font loading: 

> It is responsibility of developer to ensure that required font/s are present. ClosedXML needs font metrics and substitution tables to calculate text bounds in the font. It can’t pull them out of thin air.

https://closedxml.readthedocs.io/en/latest/tips/missing-font.html

It's not job of ClosedXML to ensure access to fonts. That falls to the developer and the documentation provides [6 possible solutions](https://closedxml.readthedocs.io/en/latest/tips/missing-font.html#solutions) to resolve the situation.

**Comment by craftsmansam** [comment]
Hi @jahav, very sorry for not responding sooner - for some reason I never was notified of your original reply to my problem report.  I realize that ClosedXML must know the font details to get sizing correct.  However in prior versions (up to .96) it magically did this without requiring UAC permissions.  Now, in version .97 onwards, the application needs UAC off (effectively administrative) privileges to call AdjustToContents().  

The linked document you reference (https://closedxml.readthedocs.io/en/latest/tips/missing-font.html#bundle-font-version-0-100) talks about missing fonts on non-Windows boxes.  I read that before I ever posted this problem report.  Windows has Calibri installed, so why would we bundle that font (or any other) when it is available by default?

The problem doesn't necessarily lie with ClosedXML, but rather with the way SixLabors.Fonts enumerates and reads/interrogates the Fonts directory.  Somehow, though, ClosedXML was able to AdjustToContents() before the switch to SixLabors.Fonts.  I don't know why the mechanism that SixLabors.Fonts uses to read fonts requires UAC to be off.  Maybe we should take this up with SixLabors.Fonts project?  But it does have a serious impact to the ClosedXML community to require UAC to be turned off (security risk).

I don't know how to describe the repro any better than I did.  Simply call AdjustToContents() as a normal user with Windows UAC turned on.  It'll throw an ArgumentException.  If you turn UAC off, it works without throwing.

**Comment by Roofy5** [comment]
Hi @jahav, this issue might be very problematic for all of the users, which are using company`s PC. They usually have UAC turn on by company`s administrator.
