### ISSUE TITLE
Method SetValue of IXLCell don't accept type Nullable

### ISSUE THREAD

**Issue by frobert35850** [ClosedXML/ClosedXML#1962]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.100

**What is the current behavior?**

Method SetValue of IXLCell don't accept long/int nullable (long?) with v0.100

**What is the expected behavior or new feature?**

Method SetValue of IXLCell accept long/int nullable (long?)

**Is this a regression from the previous version?**

with 0.97 it's possible

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
public void Main()
{
    int? i = null;
   worksheet.Cell(row, column).SetValue(i);
}
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by timunie** [comment]
Seems like this is by design. For `null` you need to do this: 

```cs
public void Main()
{
    int? i = null;
    
    if (i is null) 
        worksheet.Cell(row, column).SetValue(Blank.Value); // Sets the cell to be blank / empty
    else
        worksheet.Cell(row, column).SetValue(i);           // Sets the cell to the actual int value
}
```

------

Question to the maintainers:

Should null-values be supported at all? I may try to implement it and send a PR if I have success, because I also need this feature. For now I use the solution shown above.

**Comment by jahav** [comment]
Well, more mundane explanation is I likely made a mistake (the key mistake wa not that I didn't have a beta release).

As far as nullable numbers/DateTime/TimeSpan are concerned, there is no value in having user code littered by `cell.Value = nullableNumber ?? Blank.Value`. There is no benefit for that, what else would anyone do?

As far as conversion from string.... That was a design error. I am not happy that I convert from type of string and the output is a blank. On the other hand, that is closest behavior to how it was originally and once againt. Let's say user has a potentially null string (e.g. from webservice) and should put it to cell. Once again, the only sensible option is `cell.Value = text ?? Blank.Value`. They could use empty string instead of blank (i.e. `cell.Value = text ?? string.Empty`) in a cell, but cell with an empty string a rarity in Excel (though valid and supported) and blank is overall better option.

**Comment by timunie** [comment]
wow, that was a fast fix 👍 I'll try it soon.
