### ISSUE TITLE
I would happy to contribute in closedxml.

### ISSUE THREAD

**Issue by aspdotnetdevloper** [ClosedXML/ClosedXML#1975]
I wanted to contribute to closed xml .
Can some one guide me on below ?
I am bit difficult in starting with openxml documentation.

**Comment by jahav** [comment]
Start with annex L.2 of part 1 ISO-29500 (or its ECMA-376 counterpart), then move onto chapter 18 in an area you are interested in. The important thing to check is alway to look for MS-OI29500. Treat spec more like a primer. The spec most certainly doesn't contain sufficient information for implementation and it is sometimes incorrect. MS-OI29500 generally corrects the most blatant mistakes and provides further information that ISO-29500 lacks. Any developer will spend a lot of time in change file, save file, check underlaying xml, repeat cycle.

What area are you interested in?

At this time, the efforts of the project are to improve performance, fix reported issues, improve documentation and ensure that calc engine works correctly, because other parts rely on it. I don't really want to add features as much as to fix current ones that mostly work. Mostly means that sometimes they don't and that probability increases as you combine more of them.

CC @igitur

**Comment by aspdotnetdevloper** [comment]
Iso 29500 is paid it's not free.
Is their freee version with you ?
I wanted to learn so i can contribute to it.
And better help you.

**Comment by jahav** [comment]
They are publicly available for download at https://standards.iso.org/ittf/PubliclyAvailableStandards/index.html
Though ISO and ECMA versions are basically same. Once a new version of ISO standard releases, it is transformed into ECMA standard. If you can't find ISO, just use ECMA

**Comment by NickNack2020** [comment]
@jahav Links to the schema are provided in the [contributing.md](https://github.com/ClosedXML/ClosedXML/blob/develop/CONTRIBUTING.md). I think we should close this issue. We can continue to add anything to contributing.md that might help future developers.
