### ISSUE TITLE
Too many dependencies for most versions

### ISSUE THREAD

**Issue by yokrysty** [ClosedXML/ClosedXML#2032]
why so many dependencies for most versions and not for some of them?
I've found that versions 0.87.1 (.NET FX) and 0.96.0 (.NET) are the best for low dependencies list.

![image](https://user-images.githubusercontent.com/9500609/225896784-5974abca-f278-4757-878d-bc738c316f1f.png)

why? why? why?
![image](https://user-images.githubusercontent.com/9500609/225896809-b1a5ad19-0fea-459b-b229-53084f31b5f2.png)

why so many for linux when targeting windows?

**Comment by jahav** [comment]
They are referenced from NETStandard 1.6 that references System.Net.Http/4.3.0 that references runtime.native.System.Security.Cryptography.OpenSsl and so on.

But ultimately, it doesn't matter what is displayed in nuget dialogue, because 
1. Packages are not actually used, because every runtime, be it .NET Core/.NET Fx only type forwards dlls to it's own implementation (i.e. .NET Core has its own implementation of System.Net.Http that is used) without actually using the "referenced" packages displayed y nuget.
2. They "referenced" packages not actually put to the output directory.

Essentially, it is something that is displayed because MS used an actual packages management structure instead of creating a separate tooling for API contract only and then hacked type forwarding on top of it.

**Comment by yokrysty** [comment]
ok thanks for the explanation, my bad i didn't check the output directory
