### ISSUE TITLE
The process of saving a particular Excel file took an exceptionally long time (more than 10 min)

### ISSUE THREAD

**Issue by ZjzMisaka** [ClosedXML/ClosedXML#2074]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

The process of saving a particular Excel file took an exceptionally long time (more than 10 min).
The table in the sheets was copied from Wikipedia, and I'm not sure if that's the reason for the issue.
Please look into this issue and provide a fix or workaround. Thank you!

**What is the expected behavior or new feature?**

Successfully save more quickly.

**Is this a regression from the previous version?**

not happen in v0.96.0

## Reproducibility

**Code to reproduce problem:**
```c#
public void Main()
{
    using (XLWorkbook workbook = new XLWorkbook("H:\\AnimeReport\\AnimeList.xlsx"))
    {
        workbook.Save();
    }
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[AnimeList.xlsx](https://github.com/ClosedXML/ClosedXML/files/11349314/AnimeList.xlsx)

**Comment by jahav** [comment]
@ZjzMisaka  The file was saved slowly due to incorrect usage of `List`. After replacement of `List` with `HashSet`, the file was saved in ~1.5 seconds.

As a workaround, you can remove all hyperlinks from the workbook. 

Alternatively, you can just use development build from [develop branch](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts), see wiki instructions [how to test a development build](https://github.com/ClosedXML/ClosedXML/wiki/Development-Builds#how-to-test-a-development-build).
