### ISSUE TITLE
new XLWorkbook(memoryStream) System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by cjuarezcv** [ClosedXML/ClosedXML#2096]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

**Version of ClosedXML**

0.101.0

**What is the current behavior?**

Error when creating new XLWorkbook using memory stream "new XLWorkbook(memoryStream)":

System.NullReferenceException:  Object reference not set to an instance of an object. - at ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
at ClosedXML.Excel.XLWorkbook.LoadSheets(Stream stream)
at ClosedXML.Excel.XLWorkbook.Load(Stream stream)
at ClosedXML.Excel.XLWorkbook..ctor(Stream stream, LoadOptions loadOptions)
at ClosedXML.Excel.XLWorkbook..ctor(Stream stream)

**What is the expected behavior or new feature?**

Be able to use "new XLWorkbook(memoryStream)" for files that previously worked on version 0.100.3

**Is this a regression from the previous version?**

Yes, the files causing an exception worked with no issues on the previous version (0.100.3)

## Reproducibility
**Code to reproduce problem:**
```c#
[HttpPost]
public async Task<IActionResult> ImportPieceBOM(IFormFile iformFile)
{
        using(var ms = new MemoryStream())
        {
            await iformFile.CopyToAsync(ms); //"iformFile" is the variable containing the excel file
            var workbook = new XLWorkbook(ms); //exception happens HERE
        }
}
```

- [x ] I attached a sample spreadsheet.  (You can drag files on to this issue)
[_2202843_DT28-037.xlsx](https://github.com/ClosedXML/ClosedXML/files/11625965/_2202843_DT28-037.xlsx)

**Comment by chatay** [comment]
Hello @cjuarezcv ,

I tried the same steps to reproduce the issue with your Excel file and indeed, it is throwing the error. However, when I create another Excel file, there are no errors, and I can easily read it using var workbook = new XLWorkbook(ms);. The problem might be related to the creation of the file using NPOI instead of Excel file.

<img width="305" alt="image" src="https://github.com/ClosedXML/ClosedXML/assets/27813881/cb72d7aa-3368-4af7-8c45-a6a158585686">


Could you please check below and reply back

https://stackoverflow.com/questions/66437339/openxmlsdk-create-xlsx-closedxml-cant-read-but-npoi-epplus-can-read-and-show

**Comment by cjuarezcv** [comment]
Thanks for the follow up @chatay .  I did consider that possibility, but it looks like something also changed between ClosedXML versions 0.100.3 and 0.101.0, because this same file was working on version 0.100.3, before we upgraded to version 0.101.0.
