### ISSUE TITLE
The type initializer for \u0027SixLabors.Fonts.Tables.TableLoader\u0027 threw an exception

### ISSUE THREAD

**Issue by Mak6255** [ClosedXML/ClosedXML#2148]
I have installed ClosedXML using below command:
Install-Package ClosedXML -Verbose -IncludePrerelease

It is working on local. but moving it to server getting error "The type initializer for \u0027SixLabors.Fonts.Tables.TableLoader\u0027 threw an exception"

Locally System: working fine
Production System - not working. 

I could not create worksheet or open xlsx file.

SixLabors.Fonts.Tables.TableLoader

I tried installing SixLabors.Fonts -Version 1.0.0-beta19 but no lock 

Install-Package SixLabors.Fonts -Version 1.0.0-beta19

Any one faces the same issue, Please guide.

**Comment by jahav** [comment]
This doesn't contain any useful info to divine what is wrong, but if it is working locally, it's unlikely to be an error in ClosedXML. 

Several suggestions:
* Do try version [0.102.1](https://github.com/ClosedXML/ClosedXML/releases/tag/0.102.1) 
* Check that correct version of SixLabors.Fonts is actually loaded. E.g. correct version of AssemblyInformationalVersion contains 1.0.0-beta19 for 0.102.0 or 1.0.0 for 0.102.1. Use `typeof(SixLabors.Fonts.SystemFonts).Assembly.GetCustomAttributesData().Single(t => t.AttributeType == typeof(AssemblyInformationalVersionAttribute)).ToString()` or something.

Closing.

**Comment by Mak6255** [comment]
Thank for your Reply 

I will try to install version [0.102.1] and will let you know.

**Comment by Limitbreak4** [comment]
@Mak6255 did you solved it?

**Comment by bexoda** [comment]
I have tried the same package version but im getting the same result. Any solution?

**Comment by Mak6255** [comment]
No, It is not working and i did not get server machine for long time
so i switched to OpenXML and it is more flexible.

**Comment by vseven** [comment]
> No, It is not working and i did not get server machine for long time so i switched to OpenXML and it is more flexible.

As someone who has fought with OpenXML, a lot, I don't see how that's true.  Especially with large datatables being put into Excel (30+ columns, 80+ sheets, 3k+ rows).   

I had a similar type initializer issue.   My fix: Remove ClosedXML, remove SixLabors.Fonts, install SixLabors.Fonts 1.0.0-beta19, install ClosedXML 0.101.0.  Clean your solution and recompile.  I could not get any other version of SixLabors.Fonts to work nor could I get beta19 to work with 102 but 101 seems to work fine.

**Comment by brad302** [comment]
Does anyone happen to have any further information on this issue?

I'm having the issue locally when trying to instantiate an instance of a workbook locally via a LogicApps Standard WorkflowTriggerFunction in VS Code but the same code works in a console app.

Both projects target .NET Framework 4.7.2 ... I don't have an option regarding the framework, I'm bound to 4.7.2 ... I'm struggling and am really needing a fix or some direction on how to fix it.

LA Standard runs on the Azure Functions v4 runtime and allows you to create functions that can be called via an operation in LA but the framework it runs on is framework 4.7.2

I've done what's suggested here but no success thus far.

Ultimately, I don't care about the graphics engine at all, I simply want to load data to a number of tables in the relevant workbook.

Keen to hear if anyone has any other ideas for overcoming this error.

## UPDATE

This is the fix for anyone not wanting to deal with the graphics engine.  Thank god ...!

https://github.com/ClosedXML/ClosedXML/issues/1902

**Comment by DannySotzny** [comment]
I don't know what caused it... but restarting Visual Studio, cleaning it, and rebuilding it fixed it 🤷‍♂️

I only encountered the error when building the MSI file. The release files ran without any problems.
