### ISSUE TITLE
SixLabors.Fonts v2.0.0 changed to Commercial License

### ISSUE THREAD

**Issue by dbuhl** [ClosedXML/ClosedXML#2171]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [ ] Feature
- [x] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

1.0.0

**What is the current behavior?**

Works with SixLabors.Fonts 1.0.0 >

**What is the expected behavior or new feature?**

Will ClosedXML eventually require the SixLabors.Fonts v2.0.0 or greater as this changes to a commercial license from the Apache License? This is an important question for future planning for out application.  I would assume this will become an issue for most users of the library if this should occur.

**Is this a regression from the previous version?**

N/A

## Reproducibility

N/A

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
// N/A
```

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by jahav** [comment]
I do not plan on using `SixLabors.Fonts 2.0.0`. The primary reason is lack of support for `netstandard 2.0`.

For now, I plan to keep dependency on `SixLabors.Fonts 1.0.0 `and investigate `SkiaSharp` as a likely replacement. No concrete timeline, I would prefer to spend time on other things, but if a security bug or some other high priority issue appears, it will get priority. 

`SkiaSharp` also means the `Blazor` applications with `WebAssembly` wouldn't be able to use it (though there is an extension point), because it's a wrapper over native `Skia` library. I think `SkiaShap` is basically the only library left, based on past research into alternatives (https://github.com/ClosedXML/ClosedXML/issues/1805).

As for the `SixLabors.Fonts` split license, users of `ClosedXML` would likely be covered by Transitive Package Dependency clause, though lack of `netstandard 2.0`  makes this a moot point to investigate further. I also understand the reluctance of that license in a chain of dependencies, so switch would likely came up anyway.

This is just another fallout out of abandonement of `System.Drawing.Common` by Microsoft. The direction of `SixLabors.Fonts` (net6 only, split license) was clear from `ImageSharp`, but I hoped I would have more time than a single month between 1.0 and 2.0. Thankfully, after the last time, the code was isolated behind an interface, so it should be easier to switch.

Sidenote: if `DocumentFormat.OpenXml` dumps netstandard 2.0, ClosedXML will have to move as well. For now, they plan on keeping netstandard 2.0 even for 3.0 ([ROADMAP.md](https://github.com/dotnet/Open-XML-SDK/blob/main/docs/ROADMAP.md): _Investigate simplifying target frameworks to .NET 4.6, .NET Standard 2.0, and .NET 6_)

>
