### ISSUE TITLE
InvalidCastException when evaluating an expression inside of a LOG function

### ISSUE THREAD

**Issue by jwoodhouse23** [ClosedXML/ClosedXML#2229]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

Newest CI version says that evaluation of cell functions is not yet supported for both the working and broken book.

**Version of ClosedXML**

0.102.1

**What is the current behavior?**

When evaluating an expression inside of a LOG10(), I encounter an InvalidCastException. I have to evaluate the inner expression in a separate cell and reference that inside LOG10(). This problem also exists for LOG().

**What is the expected behavior or new feature?**

To evaluate the function correctly.

**Is this a regression from the previous version?**

Yes. Issue not present on 0.101.0

## Reproducibility
**Code to reproduce problem:**
```c#
IXLWorkbook brokenBook = new XLWorkbook("C:\\ExcelTesting\\Book1.xlsx"); //This one is broken
brokenBook.RecalculateAllFormulas();

XLWorkbook workingBook = new XLWorkbook("C:\\ExcelTesting\\Book2.xlsx"); //This one works
workingBook.RecalculateAllFormulas();
```
(Comment out one or the other to see the difference)

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[Book1.xlsx](https://github.com/ClosedXML/ClosedXML/files/13675795/Book1.xlsx)
[Book2.xlsx](https://github.com/ClosedXML/ClosedXML/files/13675796/Book2.xlsx)

**Comment by jahav** [comment]
I am pretty sure this was fixed in #2153. The root problem was that single-cell reference after binary operation was turned into 1x1 array and conversion of legacy expression then failed. 

The root problem is that functions are not evaluated per function evaluation model (third model, hopefully correct this time)
https://docs.closedxml.io/en/latest/concepts/function-evaluation.html. I am pretty sure binary operations should be evaluated like functions.

Second thing is a bug in ClosedParser, LOG10 is technically a valid address, so it is parsed as cell-function (valid from published  grammar POV, but Excel doesn't support). I will probably just remove reference token out. Excel doesn't support it and we are long way from supporting lambda functions anyway.
