### ISSUE TITLE
Unable to Open excel file having pivot table with named table range reference

### ISSUE THREAD

**Issue by spk33** [ClosedXML/ClosedXML#2309]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.102.2

**What is the current behavior?**
Not sure if this is a bug for ClosedXML or limitation for referencing OpenXML.The issue im facing is 

Unable to open xlsx file  and getting Object reference error when opening an excel file which has Pivot Tables  with source as  Named Table reference.

**What is the expected behavior or new feature?**

 to be able to open the file and read the values from the named Manager or the individual cells
 attached the sample excel file and code for reference
[testingPivotExcel.zip](https://github.com/ClosedXML/ClosedXML/files/14572516/testingPivotExcel.zip)

**Is this a regression from the previous version?**

This issue is happening in current stable version 0.102.2

## Reproducibility

**Code to reproduce problem:**
```c#
using ClosedXML.Excel;

try
{
    string excelFileName = "testPivot.xlsx";

    string excelFilePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, excelFileName);

    // Load the Excel workbook and worksheet containing the pivot table  with named table reference
    var workbook = new XLWorkbook(excelFilePath);
    var worksheet = workbook.Worksheet(1);


    var pivotTableParts = worksheet.PivotTables;
}
catch (Exception ex)
{
	throw;
}
```

- [ x] I attached a sample spreadsheet.  (You can drag files on to this issue)
![image](https://github.com/ClosedXML/ClosedXML/assets/7496315/53ccde41-6c67-4f21-8f8e-95a3508198bb)

**Comment by jahav** [comment]
Git bisect says this has been fixed in #2186/0.104.

The pivot data source of the workbook in the archive says it is `tblDropdown[Dropdown Test]`... interesting. I never realized Excel allows one column of a table as a pivot cache source. Spec say it should be _the named range that is the source of the data._.

Anyway, the pivot table before PR used to take data directly from the source (e.g. some worksheet range or table), but that is not how it should work. The PR separated the actual source and cache.

ClosedXML didn't find the actual source (and won't find today, it's a column table), so it threw an exception. Now it takes data from cache where they are and doesn't throw.
