### ISSUE TITLE
InsertRowsBelow slower than InsertData

### ISSUE THREAD

**Issue by Pitterling** [ClosedXML/ClosedXML#240]
while #210 addresses InsertData performance; 
in my test program - InsertRowsBelow is 6 times slower than InsertData
[ClosedXML-Memory-Issues](https://github.com/Pitterling/ClosedXML-Memory-Issues)

Insert 50.000 rows - v0.86
InsertRowsBelow Time elapsed: 00:00:**06.4409172**
InsertData Time elapsed: 00:00:**01.1580346**

Insert 50.000 rows - Use FastMember instead of slow Reflection #210
InsertRowsBelow Time elapsed: 00:00:06.4316558
InsertData Time elapsed: 00:00:01.0096845

**Comment by igitur** [comment]
`InsertRowsBelow` is slower than `InsertData` because `InsertRowsBelow` has to inspect all cells and adjust the cells' formula references based on the new location of the cells to which they point.

**Comment by peetn** [comment]
Is there a way to do multiple inserts across the sheet in 1 go? So it only recalculates once?
I see inserting 1 row takes 3-4sec which is too long if you need to insert 50 rows in a sheet of 100 rows. Appending rows is not an option in my case but I could try to queue all the inserts and push them in 1 go. But then again, it will probably be complex since the reference row (below which to insert) will change during that queued insert... however if I already calculate what the ‘to be’ row number would be, maybe I could just include that in the queued insert. 
Just an idea.

**Comment by igitur** [comment]
@peetn For a spreadsheet of typical width, inserting 1 row should not take 3-4s. Ensure you don't have instantiated cells somewhere far to the right of the worksheet. e.g. use `XLWorksheet.LastCellUsed(includeFormats: true)`. If it's still a problem, open a new issue (this one is closed) with code sample according to the specifications.

**Comment by peetn** [comment]
Hey, it is a problem (using 0.95.2).
I trimmed down my code but for a sheet of 24x24 (last cell used: X24) it takes 3 seconds per individual insert and for 100 rows that is 5 minutes for the inserts only.
If I try to batch the adjacent inserts, it takes about 3 seconds per batch but that is not feasible in reality.
I'll create a new issue as requested with sample code, stopwatch output and sample file (dummy data)
