### ISSUE TITLE
Workbook with e.g. FILTER formula or cell range results in not compatible excel or unexpted result 

### ISSUE THREAD

**Issue by Rand-Random** [ClosedXML/ClosedXML#2542]
## Read and complete the full issue template

Do not randomly delete sections. They are here for a reason.

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature
- [ ] Question

**Did you test against the latest CI build?**
- [x] Yes
- [ ] No

If you answered `No`, please test with [the latest development build](https://ci.appveyor.com/project/ClosedXML/ClosedXML/branch/develop/artifacts) first.

**Version of ClosedXML**

e.g. 0.104.2

**What is the current behavior?**

Excel reports error on open, when cell contains FILTER function. (hope the german screenshots are understandable)
![image](https://github.com/user-attachments/assets/283d858f-62a0-4838-9277-92d11b0680e1)
![image](https://github.com/user-attachments/assets/daef370a-ae88-483c-9f89-2b20582c4d95)

**What is the expected behavior or new feature?**

Formula should work.

**Is this a regression from the previous version?**

No.

## Reproducibility
**This is an important section. Read it carefully. Failure to do so will cause a 'RTFM' comment.**

Without a code sample, it is unlikely that your issue will get attention. Don't be lazy. Do the effort and assist the developers to reproduce your problem. Code samples should be [minimal complete and verifiable](https://stackoverflow.com/help/mcve). Sample spreadsheets should be attached whenever applicable. Remove sensitive information.

**Code to reproduce problem:**
```c#
static void Main(string[] args)
{
    WriteXlsx();
    
    var prz = new Process();
    prz.StartInfo.FileName = "dummy.xlsx";
    prz.StartInfo.UseShellExecute = true;
	prz.Start();
}

private static void WriteXlsx()
{
    using var wb = new XLWorkbook(); 
    var ws = wb.Worksheets.Add("Sheet1");
    ws.Cell("A2").FormulaA1 = "=FILTER(C:C, B:B=B2)";

    wb.SaveAs("dummy.xlsx");
}
```

- [x] I attached a sample spreadsheet.  (You can drag files on to this issue)
[dummy.xlsx](https://github.com/user-attachments/files/17966449/dummy.xlsx)

This will also give unexpected result:

```c#
static void Main(string[] args)
{
    WriteXlsx();
    
    var prz = new Process();
    prz.StartInfo.FileName = "dummy.xlsx";
    prz.StartInfo.UseShellExecute = true;
	prz.Start();
}
private static void WriteXlsx()
{
    using var wb = new XLWorkbook();
    var ws = wb.AddWorksheet();
    
    ws.Cell("B1").Value = 1000;
    ws.Cell("C1").Value = 2000;
    ws.Cell("D1").Value = 3000;

    ws.Cell("B2").Value = 1;
    ws.Cell("C2").Value = 2;
    ws.Cell("D2").Value = 3;
    
    ws.Range("A4").FormulaA1 = "SUM(B1:D1*B2:D2)";

    wb.SaveAs("dummy.xlsx");
}
```

Excel doesn't produce an error upon opening, but it cell will result in a "#VALUE!" error.

![image](https://github.com/user-attachments/assets/e06983aa-dcc3-4493-890b-1f537b83dc0a)

The specified ranges have a prefix @ removing them in excel will result in a working formula.
![image](https://github.com/user-attachments/assets/9e15bb74-de8b-4a63-9cc7-780b9514f532)

**Comment by jahav** [comment]
Use `_xlfn._xlws.FILTER` instead of `FILTER`, see https://docs.closedxml.io/en/latest/features/functions.html. I finally have a parser that can easily manipulate formulas, so this will likely be fixed (=automatically translated when setting a formula) relatively soonish (release or two).

As for @, that is something called implicit intersection and that's how Excel calculated stuff up-to-2016. Except back then it was automatically done everywhere (i.e. it wasn't shown). Excel 2019 added dynamic arrays and spills and to make it work. Excel adds (previously implicit) intersection explicitly to each formula to workbooks that were created for pre-2019 model (that included workbooks created by ClosedXML). There is no support for dynamic arrays at the moment and likely won't be for some time.

**Comment by Rand-Random** [comment]
Thanks for the very very fast response.

`_xlfn._xlws.FILTER` works like a charm, thanks.
Out of curiousity, why would ClosedXML need to manually support (manipulta/translate) this function in the first place?
How would it work with a custom function e.g. from a random excel addin? Would I also need to define a namespace pointing to the addin? 

Sorry, if that is a noob question.


`As for @` thanks for the explanation, luckily it is only something I noticed by chance and not something I currently need.

**Comment by jahav** [comment]
@Rand-Random  ClosedXML doesn't need to add the prefix. This is basically a user error, but error so unobvious/frequent to casual user that it is better to add automatic fixer. 

There is no function with name `FILTER`. There is only `_xlfn._xlws.FILTER`, see [2.2.3 Functions](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-xlsx/5d1b6d44-6fc1-4ecd-8fef-0b27406cc2bf). Using `FILTER` in a formula means using an undefined function.

But most people refer to Excel user documentation and what Excel shows in the Formula Bar. Formula bar is not a correct formula, but massaged formula to be pleasant to the user, e.g.:

* Function names are translated, e.g. `VLOOKUP` is `SVYHLEDAT` in Czech (`SVERWEIS` in German).
* In Czech, argument separator is semi-colon, e.g. `IF(A1;1;2)`.
* Structure reference for this row is shown as `SUM(Table1[@])` instead of correct `SUM(Table1[#This Row])`

As for why new functions have prefix... I don't know, but I would guess to not break compatibility with previous versions. What is some company has a workbook that does contain a VBA function they named `FILTER` (or any other new function name added to Excel)? Adding unprefixed name could leak to breakage or complicated behavior which function to choose.
