### ISSUE TITLE
TypeLoadException with DocumentFormat.OpenXml.Framework 3.2.0

### ISSUE THREAD

**Issue by jamesgurung** [ClosedXML/ClosedXML#2560]
**Do you want to request a *feature* or report a *bug*?**

Bug

**Did you test against the latest CI build?**

Yes

**Version of ClosedXML**

0.104.2

**What is the current behavior?**

Adding package references to both `ClosedXML` 0.104.2 and `DocumentFormat.OpenXml.Framework` 3.2.0 causes a `System.TypeLoadException` when saving a workbook.

**What is the expected behavior or new feature?**

The workbook should save correctly.

**Is this a regression from the previous version?**

No.

**Code to reproduce problem:**

*ConsoleApp1.csproj*
```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.2.0" />
  </ItemGroup>
</Project>
```

*Program.cs*
```c#
using var workbook = new ClosedXML.Excel.XLWorkbook();
workbook.Worksheets.Add();
using var stream = new MemoryStream();
workbook.SaveAs(stream);
```

**Exception and stack trace:**
```
Unhandled exception. System.TypeLoadException: Could not load type 'DocumentFormat.OpenXml.Builder.PackageInitializerDelegate`1' from assembly 'DocumentFormat.OpenXml.Framework, Version=3.2.0.0, Culture=neutral, PublicKeyToken=8fb06cb64d019a17'.
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(Stream stream, SpreadsheetDocumentType type, Boolean autoSave)
   at DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(Stream stream, SpreadsheetDocumentType type)
   at ClosedXML.Excel.XLWorkbook.CreatePackage(Stream stream, Boolean newStream, SpreadsheetDocumentType spreadsheetDocumentType, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, SaveOptions options)
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream, Boolean validate, Boolean evaluateFormulae)
   at ClosedXML.Excel.XLWorkbook.SaveAs(Stream stream)
   at Program.<Main>$(String[] args) in D:\Projects\ConsoleApp1\Program.cs:line 4
```

**Comment by jahav** [comment]
I am going to punt this to OpenXML SDK, because that is in that library. Minimal reproducible sample was adjusted accordingly.

I guess the reason is the change of an internal delegate name from `PackageInitializerDelegate` in 3.1.1 ([link](https://github.com/dotnet/Open-XML-SDK/blob/v3.1.1/src/DocumentFormat.OpenXml.Framework/Builder/IPackageBuilder%7BTPackage%7D.cs#L14)) to `PackageDelegate` in 3.2.0 ([link](https://github.com/dotnet/Open-XML-SDK/blob/v3.2.0/src/DocumentFormat.OpenXml.Framework/Builder/IPackageBuilder%7BTPackage%7D.cs#L14)).

DocumentFormat.OpenXML (3.1.1) tries to load expected delegate `PackageInitializerDelegate` (that should be present, at least it was in 3.1.1, it is exposed through `InternalsVisibleTo`), likely though `IPackageBuilder`, but the actual library doesn't contain it and that is why it fails.

Minimal reproducible example:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.2.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.1" />
  </ItemGroup>
</Project>
```
```csharp
using var stream = new MemoryStream();
DocumentFormat.OpenXml.Packaging.SpreadsheetDocument.Create(stream, DocumentFormat.OpenXml.SpreadsheetDocumentType.Workbook);
```

**Comment by jahav** [comment]
So please open the issue in the `https://github.com/dotnet/Open-XML-SDK` repository.
