### ISSUE TITLE
Copying style from one range to apply it on another

### ISSUE THREAD

**Issue by Granathar** [ClosedXML/ClosedXML#273]
Is copying styles possible in ClosedXML? I have some range being a header for another range. I want both of them having the same style. The lower level range does not have it's own style because it's supposed to copy style of it's "owner". Owner's style is working fine, but when I try to copy it - child header has style default for whole worksheet. He did not receive style from his parent, but some static variable.

```c#
if (Owner != null)
 {
       HeaderStyle = Owner.HeaderStyle;
 }
```

And header style is:
```c#
public IXLStyle HeaderStyle
{
     get
     {
          return HeaderRange.Style;
     }
     set
     {
          HeaderRange.Style = value;
     }
}
```
Of course HeaderRange is IXLRange informing block about his location in document.

It should be shallow copy of this style which is fine with me - but it doesn't even do shallow copy. Am I doing something wrong, is it bug or designed behavior?

**Comment by vbjay** [comment]
I did suggest this in #86. I think this is a great idea. What we could do
is implement the same idea as a cell style in a datagridview. See
https://msdn.microsoft.com/en-us/library/1yef90x0(v=vs.110).aspx

**Comment by Granathar** [comment]
Wait, so every cell has it's own style? They are not referencing this static-default one? What's the logic behind this? Every cell should reference default style unless user will change it (then setter should create deep copy of default, modify it and reference it instead of default) or give them brand new style (which is not even possible right now).

**Comment by vbjay** [comment]
I agree. Why I suggested it.

**Comment by NeededAnUnusedName** [comment]
Hello, 
the Topic matches, so I'll ask here:
I'm trying to copy the Style (Background Color would be enough) from one Cell to a Range of Cells. 
Which sometimes works, sometimes does not work, sometimes it works only half way and in my "live .XLSX" it sometimes does very weird things. ^^
My Test Code:
> Filename = @"C:\MyTemp\empty.xlsx";
> String Worksheet = "Tabelle1";
> using (XLWorkbook workbook = new XLWorkbook(Filename, XLEventTracking.Disabled))
> using (IXLWorksheet sheetXML = workbook.Worksheet(Worksheet))
>            {
>               IXLCell defaultcell = sheetXML.Cell(1, 1);
>               IXLRange setColorRange = sheetXML.Range(2, 1, 2, 5);
>               //foreach (IXLCell cell in setColorRange.Cells())
>                //{
>                //    cell.Style.Fill = defaultcell.Style.Fill;                        
>                //}
>                int count = setColorRange.Cells().Count();
>                for(int i = 1; i <= count; i++)
>                {
>                    IXLCell cell = setColorRange.Cell(1, i);
>                    cell.Style.Fill = defaultcell.Style.Fill;
>                    //cell.Style = defaultcell.Style;
>                    //System.Threading.Thread.Sleep(1000);
>                }
>                workbook.Save(false);
>            }

The XLSX File is empty, except for cell A2,B2,C2,D2,E2, which I set to a random(blue) background Color.  Now I want the defaultcell to copy its default background Color to those 5 Cells. 
As mentioned above I get different results using the same code and I want to know why and how to stop that. Most of the time it only paints A2, and leaves the rest blue. Sometimes it manages 3 Cells, rest blue. When using Cell.Style instead of Style.Fill (or Style.Fill.BackgroundColor) it works as a charm in this XLSX, and it did so in my much bigger "live XLSX". But not anymore. Now when using this aproach it even paints the "defaultCell" blue,... 
Why does it behave so unpredictable? How do I stop that? What am I doing wrong?

I would also like to mention, that if I debug that above code and hit the workbook.Save(false) part, it SOMETIMES breaks with a null exception, when running the code without debugging that never happens.

Thanks for any help in advance

**Comment by vbjay** [comment]
Can you capture the call stack when there is a null exception?

**Comment by NeededAnUnusedName** [comment]
Sure, but its pretty german. 

>System.ArgumentNullException: Der Wert darf nicht NULL sein. Parametername: source

>    bei System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, >IEqualityComparer`1 comparer)
>   bei System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value)
>   bei ClosedXML.Excel.XLHyperlink.get_InternalAddress() in >C:\Projects\ClosedXML\ClosedXML\Excel\Hyperlinks\XLHyperlink_public.cs:Zeile 74.
>   bei ClosedXML.Excel.XLWorkbook.GenerateWorksheetPartContent(WorksheetPart worksheetPart, >XLWorksheet xlWorksheet, SaveContext context) in >C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 4347.
>   bei ClosedXML.Excel.XLWorkbook.CreateParts(SpreadsheetDocument document) in >C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 314.
>   bei ClosedXML.Excel.XLWorkbook.CreatePackage(String filePath, SpreadsheetDocumentType >spreadsheetDocumentType, Boolean validate) in >C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook_Save.cs:Zeile 117.
>   bei ClosedXML.Excel.XLWorkbook.Save(Boolean validate) in >C:\Projects\ClosedXML\ClosedXML\Excel\XLWorkbook.cs:Zeile 452.
>   bei ClosedXML_insertTest.Program.Main(String[] args) in C:\VisualStudio2015\Projects\ClosedXML->insertTest\ClosedXML-insertTest\Program.cs:Zeile 39.

As mentioned above this does not always happen. (Took me 6 aproaches to reproduce, I dont know exactly but I think it only happens when I look into the IXLRange/IXLCell Objects to view its values (eg. Adress) 
Can you tell me something about that weird Background behavoir? Maybe point me in the right direction? I have been working on this project for weeks/month now and was relying on that to work... -.-

**Comment by NeededAnUnusedName** [comment]
I managed to get a new unwanted behavoir: 
using this:
> cell.Style.Fill.SetBackgroundColor(defaultcell.Style.Fill.BackgroundColor);
in my foreach loop (see 2-3 posts above) leaves me with 5 **black** cells. Now where did that black color come from, the "defaultcell" is white/transparent/defaultStyle, not black. oO

**Comment by igitur** [comment]
@NeededAnUnusedName That is an unrelated bug. Please file a new issue with suitable code to reproduce and upload your Excel file.

**Comment by igitur** [comment]
For this issue, yes, a central style repository would be one solution, as people have pointed out many times. However, this would require a significant change to the ClosedXML API, which I must thoroughly investigate. 

Take this sample code:
```c#
using (var wb = new XLWorkbook())
using (var ws = wb.Worksheets.Add("Sheet1"))
{
    var a1 = ws.Cell("A1");
    var a2 = ws.Cell("A2");

    c1.Style.Fill.BackgroundColor = XLColor.Red;
    c2.Style.Fill.BackgroundColor = XLColor.Blue;
}
```
With the current codebase, cell `C1` would indeed be red and `C2` would be blue, as is expected.

Now let's imagine we implement a style repository. That means `c1.Style` points to some object in a shared repository. `c2.Style` also points to an object in the repository. When you open a new spreadsheet, `c1` and `c2` would both have the default styles (i.e. no background colour). Both cells would have the same `Style` instance, or in other words `Object.ReferenceEquals(c1.Style, c2.Style)` would evaluate to `true`. That means, in the above code sample, when you set `c2`'s background colour to `XLColor.Blue`, you would be changing this single instance's colour. Because `c1` also uses that style, both `C1` and `C2` would have a blue background. This is unintuitive and would break a lot of existing codebases. I doubt I would allow that. 

If we use a style repository, we would need some hack to do an implicit/invisible `c2.Style = new Style()` first when one of the `Style` instance's child properties is changed. I've been looking for solutions, but haven't found a pattern that solves this yet. If someone has a practical application (i.e. real code) that can solve this, please help.

cc @Pyropace

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/1yef90x0(v=vs.110).aspx

**Comment by Pyropace** [comment]
> Now let's imagine we implement a style repository. That means c1.Style points to some object in a shared repository. c2.Style also points to an object in the repository. When you open a new spreadsheet, c1 and c2 would both have the default styles (i.e. no background colour). Both cells would have the same Style instance, or in other words Object.ReferenceEquals(c1.Style, c2.Style) would evaluate to true. That means, in the above code sample, when you set c2's background colour to XLColor.Blue, you would be changing this single instance's colour. Because c1 also uses that style, both C1 and C2 would have a blue background. This is unintuitive and would break a lot of existing codebases. I doubt I would allow that.

it would have to be a mapper, that knows what cells are referencing what style objects if a "cell" creates or changes a shared object that is referenced by other cells except for its self, then it will need to create a new shared object for the given cell.

**Comment by vbjay** [comment]
Important details in the article.
As mentioned above, getting the value of a style property automatically
instantiates a new DataGridViewCellStyle object if the property has not
been previously set. To avoid creating these objects unnecessarily, the row
and column classes have a HasDefaultCellStyle property that you can check
to determine whether the DefaultCellStyle property has been set. Similarly,
the cell classes have a HasStyle property that indicates whether
the Style property has been set.

**Comment by devMagics** [comment]
i have this issue too when style rows when rows count near 2000 rows   this issue System.OutOfMemoryException exception 

       using (var ws = wb.AddWorksheet(mydataTable, "MyDataName"))  
                {
                    for (int i = 2; i < ws.Rows().Count(); i++)
                    {
                        if (ws.Row(i).Cell(1).Value.ToString() == "MyCondition")
                        {
                            ws.Row(i).Style.Fill.SetBackgroundColor(XLColor.LightGray);
                        }
                        else
                        {
                            ws.Row(i).Style.Fill.BackgroundColor=XLColor.LightYellow;
                        }
                    }
                    ws.Tables.FirstOrDefault().ShowAutoFilter = false;
                }

**Comment by vbjay** [comment]
https://github.com/closedxml/closedxml/wiki/Conditional-Formatting

**Comment by devMagics** [comment]
//style full worksheet background
      ws.Style.Fill.BackgroundColor = XLColor.LightYellow;
    
     //style for one cell
     ws.AddConditionalFormat().WhenEquals("MYSearchString").Fill.BackgroundColor = XLColor.LightGray;

i need to style full row based on cell value, without looping each row ??

**Comment by vbjay** [comment]
Probably don't need to do the whole sheet.  just the used area.

**Comment by devMagics** [comment]
in my case i need to format the whole row ,there is any solution for this case?

**Comment by vbjay** [comment]
Whole row is fine. I'm saying don't add a condition to the whole sheet. Add
it to the used range.

**Comment by devMagics** [comment]
i get your advice , but the only solution i know for this issue loop the whole sheet row by row and change the background color for my sheet its reached to 10000 rows  and i get exception System.OutOfMemoryException , what should i do ?

**Comment by vbjay** [comment]
https://github.com/closedxml/closedxml/wiki/Simplifying-your-life

Do you get it now?

**Comment by devMagics** [comment]
thanks , i found solution to my issue by using lambda expression 
[](https://github.com/closedxml/closedxml/wiki/Using-Lambda-Expressions)

**Comment by igitur** [comment]
@devMagics Mind sharing your code? If it's useful, I might add it to the codebase.

**Comment by Pankraty** [comment]
Styles handling has been redesigned completely so I assume this issue may be closed. Now applying a style from one range to another should work as expected. If it does not please open another issue.
