### ISSUE TITLE
"Pivot Tables Values Problem" 

### ISSUE THREAD

**Issue by Pyropace** [ClosedXML/ClosedXML#39]
File with Pivot Table fails to open 

https://closedxml.codeplex.com/workitem/8466

**Comment by Sharpiro** [comment]
My company only uses Excel 2010 in their environment and I have an example where adding a pivot tables breaks my spreadsheet 100% of the time in 2010.

https://github.com/ClosedXML/ClosedXML/compare/develop...Sharpiro:feature/pivot-tables-error

**Comment by Pyropace** [comment]
Thanks for the input. I will look into this today

**Comment by igitur** [comment]
While ClosedXML should not generate invalid files. However, your code doesn't describe a pivot table fully. You should add RowLabels and Value fields. For example, adding to your code:

```c#
//this code block will break it
var range = worksheet.Range(1, 1, maxCount, 4);
var ptSheet = wb.Worksheets.Add("PivotTableX");
var pivotTable = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), range);
// Added code:
pivotTable.RowLabels.Add("Item");
var pv = pivotTable.Values.Add("Added");
pv.SummaryFormula = XLPivotSummary.Count;
```
will result in a valid Excel file.

**Comment by vbjay** [comment]
If there are pieces needed like that then we need to include them in add
new. It should create a valid pivot table. Even if the row table is blank,
I expect add new to just work.
On Thu, Oct 6, 2016, 11:17 AM Francois Botha <notifications@github.com>
wrote:

While ClosedXML should not generate invalid files. However, your code
doesn't describe a pivot table fully. You should add RowLabels and Value
fields. For example, adding to your code:

//this code block will break itvar range = worksheet.Range(1, 1,
maxCount, 4);var ptSheet = wb.Worksheets.Add("PivotTableX");var
pivotTable = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1,
1), range);// Added code:
pivotTable.RowLabels.Add("Item");var pv = pivotTable.Values.Add("Added");
pv.SummaryFormula = XLPivotSummary.Count;

will result in a valid Excel file.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ClosedXML/ClosedXML/issues/39#issuecomment-251994395>,
or mute the thread

**Comment by igitur** [comment]
@vbjay Agreed, but the constructor can possibly get very complicated if one has to allow for every bit of information. Part of the goal of this project is to keep a nice syntax. I would rather validate the pivot table when the file is written and throw an informative exception if the pivot table is incomplete. 

Pivot tables aren't the only thing affected by this. When we (hopefully soon) introduce charting, query tables, etc, we are going to face similar problems.

**Comment by vbjay** [comment]
Then we need a validation functionality that says you are missing x and y
to make this a valid [type].

**Comment by vbjay** [comment]
It should be an interface and the XML comments need to be clear that the
validation is not the same as excel data validation. It could return
validation failure objects that provide details on what is needed to fix
the validation issue.

**Comment by igitur** [comment]
Good suggestions. Turn them into a pull request.

**Comment by vbjay** [comment]
I keep getting ideas after hitting send. :) Also not just save. It should
be able to get called any time desired.

On Thu, Oct 6, 2016, 11:32 AM Jay Asbury <vbjay.net@gmail.com> wrote:

It should be an interface and the XML comments need to be clear that the
validation is not the same as excel data validation. It could return
validation failure objects that provide details on what is needed to fix
the validation issue.

On Thu, Oct 6, 2016, 11:27 AM Jay Asbury <vbjay.net@gmail.com> wrote:

Then we need a validation functionality that says you are missing x and y
to make this a valid [type].

On Thu, Oct 6, 2016, 11:24 AM Francois Botha <notifications@github.com>
wrote:

@vbjay <https://github.com/vbjay> Agreed, but the constructor can possibly
get very complicated if one has to allow for every bit of information. Part
of the goal of this project is to keep a nice syntax. I would rather
validate the pivot table when the file is written and throw an informative
exception if the pivot table is incomplete.

Pivot tables aren't the only thing affected by this. When we (hopefully
soon) introduce charting, query tables, etc, we are going to face similar
problems.

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/ClosedXML/ClosedXML/issues/39#issuecomment-251996843>,
or mute the thread

**Comment by Sharpiro** [comment]
I think there is perhaps more to it than just invalid initialization of the pivot table.

In the below code, adding an additional "value" to the pivot table will again break the 2010 spreadsheet.  Perhaps I am using the API incorrectly, but this is a valid configuration when manually creating the pivot table.

```
var range = worksheet.Range(1, 1, maxCount, 4);
var ptSheet = wb.Worksheets.Add("PivotTableX");
var pivotTable = ptSheet.PivotTables.AddNew("PivotTable", ptSheet.Cell(1, 1), range);

pivotTable.RowLabels.Add("Item");
pivotTable.Values.Add("Added").SummaryFormula = XLPivotSummary.Count;
//this line will break it
pivotTable.Values.Add("Removed").SummaryFormula = XLPivotSummary.Count;
```

I updated my feature: https://github.com/ClosedXML/ClosedXML/compare/develop...Sharpiro:feature/pivot-tables-error

**Comment by DeveloperFarris** [comment]
Is it possible to add multiple fields as Value column through ClosedXML? I only see examples using one field.

**Comment by igitur** [comment]
PR #99 could possibly fix some of your needs. Specifically, multiple pivot value fields are now possible. Please test it and let us know.

**Comment by igitur** [comment]
@vbjay The develop branch also now has an overload for XLWorkbook.Save(bool validate). Setting validate = true runs a validator on the generated package and should show any errors. I don't think it will show ALL errors, but it's a step in the right direction. In the DEBUG configuration, the validation occurs by default. It is disabled by default in the RELEASE configuration, but you can specify the parameter in the overload.
