### ISSUE TITLE
Table column header with line break throw exception

### ISSUE THREAD

**Issue by marcinKotynia** [ClosedXML/ClosedXML#392]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
EXception  System.ArgumentOutOfRangeException: 'Specified argument was out of the range of valid values.'

**If the current behavior is a bug, please provide the steps to reproduce and 
if possible a minimal demo of the problem with a sample spreadsheet.**

Attached file - standard Excel template
XLWorkbook workBook = new XLWorkbook(path to attached file);  << will throw error

I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
public void Main()
{
 XLWorkbook workBook = new XLWorkbook(path to attached file)); 
}
```
[Test1.xlsx](https://github.com/ClosedXML/ClosedXML/files/1141269/Test1.xlsx)

**Comment by igitur** [comment]
The line breaks in the table headers are using a lookup error. I'll look into it, but maybe you want to consider a workaround in the meantime.

**Comment by marcinKotynia** [comment]
Thank You very much,  works now.

**Comment by igitur** [comment]
[ClosedXML v0.89.0-beta1](https://www.nuget.org/packages/ClosedXML/0.89.0-beta1) has been published and is ready for your testing.

**Comment by Nasoki-Koide** [comment]
(I used an AI to translate the following sentences from Japanese into English.)
I've encountered the same issue. I believe the problem is caused by the following code in the XLTable class:

```
public Int32 GetFieldIndex(String name)
        {
            // There is a discrepancy in the way headers with line breaks are stored.
            // The entry in the table definition will contain \r\n
            // but the shared string value of the actual cell will contain only \n
            name = name.Replace("\r\n", "\n");
            if (FieldNames.TryGetValue(name, out IXLTableField tableField))
                return tableField.Index;

            throw new ArgumentOutOfRangeException("The header row doesn't contain field name '" + name + "'.");
        }
```
This code works correctly with manually created Excel files. However, when an Excel file is edited, saved, and then reopened using ClosedXML, the line breaks within the field names (presumably stored in the FieldNames dictionary) are found to be \r\n. This creates a mismatch with the name parameter, which is normalized to \n by the name.Replace("\r\n", "\n"); line, preventing TryGetValue from finding the correct field.

A solution is needed to consistently handle line ending conventions for both scenarios.
