### ISSUE TITLE
Allow Access to lower level xml

### ISSUE THREAD

**Issue by AmirBosch** [ClosedXML/ClosedXML#45]

**Comment by rbev** [comment]
This would be great, it would provide the ability to work around some of the missing features.

**Comment by igitur** [comment]
I want to look at this at some stage. I thought that we could raise events during the save process and the user can subscribe to those events to handle the underlying XML in whichever way he wants to.

But we can't do this all in one go. On which elements should we focus on first? Maybe just package parts as a whole, e.g. `styles.xml`, `themes.xml`, `sheet1.xml`, etc, instead individual `<c>` (cell) elements.

**Comment by jahav** [comment]
I am closing this ticket, because I don't think this is a good approach. ClosedXML should be improved to handle missing features and any hand-waving or xml-intercepting should be left out of library. ClosedXML is already patching the original fiule and that is good enough.

Also, streaming saving is the future and modifying xml that is being streamed directly from ClosedXML internal structures without an access to DOM would be a horrible task with a horrible API.
