### ISSUE TITLE
Missing XLRichString.AddText() overloads for XLHFPredefinedText enum

### ISSUE THREAD

**Issue by koen-debacker** [ClosedXML/ClosedXML#465]
**Do you want to request a *feature* or report a *bug*?**
- [ ] Bug
- [x] Feature

**Version of ClosedXML**

0.88.0

**What is the current behavior?**

The method `AddText(XLHFPredefinedText predefinedText)` doesn't exist in `XLRichString`, but does in `XLHFItem`.

**What is the expected behavior or new feature?**

The same overloads for AddText in XLRichString as in XLHFItem.

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Code to reproduce problem:**
```c#
ws.PageSetup.Header.Right
    .AddText(XLHFPredefinedText.Date)
    .AddText(" ")
    .AddText(XLHFPredefinedText.Time); // This line doesn't work unfortunately.
```

Instead of the above code I have to do this:
```c#
ws.PageSetup.Header.Right.AddText(XLHFPredefinedText.Date).AddText(" ");
ws.PageSetup.Header.Right.AddText(XLHFPredefinedText.Time);
```

**Comment by igitur** [comment]
Thanks. I thought it might be a simple fix, but it's not. `AddText()` returns `IXLRichText` which is used in other places in the project, e.g. in cell comments. It's therefore not trivial to add header/footer related methods to this.

**Comment by jahav** [comment]
I am closing this, because I don't want to introduce another API at this time. Also, it's 7 years stale.

The `XLRichString` and its siblings (in this case `IXLHFItem`) especially, because the actual class used in the ClosedXML has been changed to immutable class. Immutable rich text can be stored in a shared string table along with all texts of cells. 

To keep everything working, the interfaces were kept and adapters were added to keep mutable API contract mostly intact. Adapters sometimes encounter rough edges (read subtle bugs) and it would be best to redesign rich text and related stuff from ground up.
