### ISSUE TITLE
The Formula AGGREGATE first comes up with #name in excel spreadsheet

### ISSUE THREAD

**Issue by gcs278** [ClosedXML/ClosedXML#562]
## Read and complete the full issue template

**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

e.g. 0.87.1

**What is the current behavior?**

When attempting to use the aggregate formula, it successfully puts the formula in the cell, but comes up with an error "#NAME?". This error goes away when I go to edit the cell and press enter again.

**What is the expected behavior or new feature?**

I should be able to put the AGGREGATE formula in the spreadsheet without getting #NAME? error.
Is this function not supported at all or is this a bug?

**Did this work in previous versions of our tool?  Which versions?**

No

## Reproducibility

worksheet.Cell("H7").FormulaA1 = "=AGGREGATE( 9, 5, "H1:H6")"

- [ ] I attached a sample spreadsheet.  (You can drag files on to this issue)

**Comment by igitur** [comment]
Not a complete code sample. RTFM

**Comment by jongleur1983** [comment]
I'm working on completimg the function support since a few weeks, and I'm pretty sure Aggregate is not yet implemented.
I skipped it as I wanted to support all different aggregation functions first.

So the behaviour you describe is expected: The calc engine in the library can't calculate the result of the formula. As a consequence the evaluation throws a nameexception in the document (= unknown function name), but whenever you enter a cell and press enter Excel triggers a new calculation, that's why the correct result appears.

I'll try tonotify you here once aggregate is implemented - or feel free to do it yourself.
See issue #52 for reference.

**Comment by igitur** [comment]
Excel should still be able to evaluate the formula if you don't save the file with formula evaluation on. This is why I ask for complete code examples in the issue template... so that I can figure out what you're doing.

**Comment by wooltown62** [comment]
Problem solved at least in XLSXWRITER:
http://xlsxwriter.readthedocs.io/working_with_formulas.html

You MUST use _xlfn.AGGREGATE instead of only AGGREGATE

worksheet.write_formula(0, column,'="Median: " & ROUND(_xlfn.AGGREGATE(12,7,INDIRECT(TEXT(CONCATENATE(ADDRESS(2,' + str(column + 1) + '),":",ADDRESS(10000,' + str(column + 1) + ')),1))),3) & ", Mean: " & ROUND(_xlfn.AGGREGATE(1,7,INDIRECT(TEXT(CONCATENATE(ADDRESS(2,' + str(column + 1) + '),":",ADDRESS(1000,' + str(column + 1) + ')),1))),4) & CHAR(10) & CHAR(10) & "' + sheet[1] + '/' + sheet[2] + '"', formatWrap)
