### ISSUE TITLE
Object Creation Validation

### ISSUE THREAD

**Issue by vbjay** [ClosedXML/ClosedXML#60]
We need an interface that we can implement that will process the object and make sure all needed things are there and meet other validation requirements. The result can be an ienumerable<ClosedXML.ObjectValidationFailure>. When saving iterate through all objects implementing the interface. The result objects need to express the issue and how to fix. Example pivot tables need row labels.

**Comment by igitur** [comment]
#62 uses OpenXmlValidator() to validate the SpreadSheetDocument package. Not sure whether this covers all our use cases, but it should do most of the heavy lifting.

**Comment by jahav** [comment]
I favor the "always valid model" approach. When state of workbook is changed through API, the workbook should be always valid (or exception should be thrown), just like Excel does it. It can use placeholder/default values, but generally method should generally work, unless some kind of invariant has been violated (e.g. unique table name -> exception). Possibly Try* methods.

The proposed `IEnumerable<ClosedXML.ObjectValidationFailure>` doesn't conform to this to this approach. That approach is more suited to GUI applications where user can interactively fix something than to automatic processing using a code, which is what ClosedXML mostly does.

The issue is from 2016, and thus stale and I am closing it.

Sidenote: I should have to write API design book, so there is some semi-unified behavior of methods, exceptions, ect..
