### ISSUE TITLE
Inserting rows above/below rows with range formatting and data validation causes Closed XML to hang

### ISSUE THREAD

**Issue by jaylittle** [ClosedXML/ClosedXML#680]
**Do you want to request a *feature* or report a *bug*?**
- [x] Bug
- [ ] Feature

**Version of ClosedXML**

0.91.0

**What is the current behavior?**

Execution does not complete.  It will hang on the InsertRowsAbove(1) call near the end.

**What is the expected behavior or new feature?**

Execution should complete.  Closed XML should not hang.  This code should produce a simple Excel file.

**Did this work in previous versions of our tool?  Which versions?**

No.  We have tried several versions and have been able to consistently reproduce this issue.  This can be replicated in 0.87.1 very easily - you just need to change XLDataType enum references to XLCellValues.

## Reproducibility

**Code to reproduce problem:**
```c#
private const string OUTPUT_FILE = "c:\\temp\\test_output.xlsx";

static void Main(string[] args)
{
  //If output file already exists, nuke it
  if (System.IO.File.Exists(OUTPUT_FILE))
  {
    System.IO.File.Delete(OUTPUT_FILE);
  }

  //Prep book and sheets
  var workbook = new ClosedXML.Excel.XLWorkbook();
  var dataWorksheet = workbook.AddWorksheet("Data");
  var listWorksheet = workbook.AddWorksheet("Lists");

  //Setup List Sheet
  listWorksheet.Cell(1, 1).Value = "List";
  for (var rowptr = 2; rowptr <= 101; rowptr++)
  {
    listWorksheet.Cell(rowptr, 1).Value = (rowptr - 1).ToString();
    listWorksheet.Cell(rowptr, 1).SetValue<string>((rowptr - 1).ToString());
    listWorksheet.Cell(rowptr, 1).DataType = ClosedXML.Excel.XLDataType.Text;
  }

  //Setup Data Validation (comment last two lines to prevent breakage)
  var listRange = listWorksheet.Range(2, 1, 101, 1);
  var ddValidation = dataWorksheet.Range(2, 1, 9999, 1).SetDataValidation();
  ddValidation.List(listRange, true);
  ddValidation.AllowedValues = ClosedXML.Excel.XLAllowedValues.List;

  //Setup Data Sheet (comment last line to prevent breakage)
  dataWorksheet.Cell(1, 1).Value = "Data";
  dataWorksheet.Range(2, 1, 9999, 1).DataType = ClosedXML.Excel.XLDataType.Text;

  //Add Data to be Validated
  var rnd = new Random();
  for (var rowptr = 2; rowptr <= 11; rowptr++)
  {
    dataWorksheet.Cell(rowptr, 1).SetValue<string>(rnd.Next(1, 100).ToString());
  }

  //Insert a row (comment this line to prevent breakage)
  dataWorksheet.Row(2).InsertRowsAbove(1);

  //Save it
  workbook.SaveAs(OUTPUT_FILE);
}
```

**Comment by Pankraty** [comment]
The reason is that DataValidation rules are splitting into pieces on row insertion. So if there were 10 cells in a range there will be 10 DataValidation rules; 9999-cells-wide range would become 9999 DataValidation rules and so on. 
@igitur do you mind if I proceed with this issue?

**Comment by igitur** [comment]
@Pankraty Please feel free to go ahead, but if it's a big PR, please check with me first and let's decide together on how to approach it.

**Comment by jaylittle** [comment]
That's very interesting.  Why does commenting out the line that sets the data type for the range prevent it from happening then?  In my testing is was the combination of the data type and the validation being set on the range that ultimately resulted in the issue.

In any event, I appreciate you all taking time to look at the problem.  Thanks!

**Comment by Pankraty** [comment]
@igitur, you may see the draft changes in this branch: https://github.com/Pankraty/ClosedXML/tree/680_DataValidation
First of all, I added some tests and found that DataValidation items behavior differs depending on whether cells in the range are empty or not. If they are empty the range is not shifted which is wrong; otherwise, the range is burst into chunks which is wrong too.
Then I made XLCell.DataValidation getter "non-invasive" so it would not create a new validation rule each time this field is accessed. That is why I had to modify existing tests too. 
These changes basically fixed the original issue, ClosedXML does not halt anymore. 
The tricky part that is still to be done is shifting and copying DataValidation formulas. Now they are stored as a plain text, I suggest using the same approach as for ConditionalFormat where they are processed as ```XLDictionary<XLFormula>```.

After all this fixed I would also check what's going on if multiple rules are applied to the same cell (for example, when the cell lays in an intersection of two range with different rules). In Excel, the user is asked whether he wants to modify an existing rule and if he agrees the range is separated. This guarantees that a cell can only have a single DataValidation rule. But this is kind of advanced feature, that can be moved to a separate task and be postponed for a while.

**Comment by Pankraty** [comment]
>  I suggest using the same approach as for ConditionalFormat where they are processed as XLDictionary<XLFormula>.

Huh. I did not realize that conditional formats' formulas are not shifted properly either. Guess I will report another bug.
